import type { FunctionalGroupPattern } from "../../types";

export const halogenGroups: FunctionalGroupPattern[] = [
  {
    name: "Halogen",
    priority: 27,
    nomenclaturePriority: 21,
    confidence: "High",
    suffix: "Never suffix",
    prefix: "fluoro, chloro, bromo, iodo",
    smarts: "[F,Cl,Br,I]",
    displaySmarts: "[F,Cl,Br,I]",
    mcatNote:
      "Halogens are electronegative substituents. In organic molecules they are named as fluoro, chloro, bromo, or iodo substituents.",
    category: "functionalGroup",
  },
  {
    name: "Haloalkane",
    priority: 27.1,
    nomenclaturePriority: 21.1,
    confidence: "High",
    suffix: "Never suffix",
    prefix: "halo",
    equivalentNames: ["alkyl halide"],
    smarts: "[CX4][F,Cl,Br,I]",
    displaySmarts: "[CX4][F,Cl,Br,I]",
    mcatNote:
      "Haloalkanes contain a halogen attached to an sp3 carbon. They readily undergo SN1, SN2, E1, and E2 reactions.",
    category: "functionalGroup",
  },
  {
    name: "Vinyl halide",
    priority: 27.15,
    nomenclaturePriority: 21.15,
    confidence: "High",
    suffix: "Never suffix",
    prefix: "vinyl halo",
    equivalentNames: ["vinylic halide", "alkenyl halide"],
    smarts: "[CX3]=[CX3][F,Cl,Br,I]",
    displaySmarts: "[CX3]=[CX3][F,Cl,Br,I]",
    mcatNote:
      "Vinyl halides have a halogen directly attached to an alkene carbon. This is different from an allylic halide, where the halogen is one carbon away from the alkene.",
    category: "functionalGroup",
  },
  {
    name: "Allylic halide",
    priority: 27.2,
    nomenclaturePriority: 21.2,
    confidence: "High",
    suffix: "Never suffix",
    prefix: "allylic halo",
    equivalentNames: ["allyl halide"],
    smarts: "[CX3]=[CX3][CX4][F,Cl,Br,I]",
    displaySmarts: "[CX3]=[CX3][CX4][F,Cl,Br,I]",
    mcatNote:
      "Allylic halides have a halogen on the sp3 carbon adjacent to an alkene. Their intermediates are resonance-stabilized, making substitution reactions faster.",
    category: "functionalGroup",
  },
  {
    name: "Benzyl halide",
    priority: 27.3,
    nomenclaturePriority: 21.3,
    confidence: "High",
    suffix: "Never suffix",
    prefix: "benzyl halo",
    equivalentNames: ["benzylic halide", "phenylmethyl halide"],
    smarts:
      "[cR1]1[cR1][cR1][cR1][cR1][cR1]1[CX4H2;!R][F,Cl,Br,I]",
    displaySmarts: "[cR1][CX4H2;!R][F,Cl,Br,I]",
    mcatNote:
      "Benzyl halides contain a halogen on the benzylic CH2 carbon, Ph-CH2-X. This is different from a halobenzene or aryl halide, where the halogen is directly attached to the aromatic ring.",
    category: "functionalGroup",
  },
  {
    name: "Geminal dihalide",
    priority: 27.4,
    nomenclaturePriority: 21.4,
    confidence: "Medium",
    suffix: "Never suffix",
    prefix: "gem-dihalo",
    equivalentNames: ["1,1-dihalide", "geminal dihalo compound"],
    smarts: "[CX4]([F,Cl,Br,I])([F,Cl,Br,I])",
    displaySmarts: "[CX4]([F,Cl,Br,I])([F,Cl,Br,I])",
    mcatNote:
      "Geminal dihalides contain two halogens on the same carbon atom. They are useful synthetic intermediates.",
    category: "functionalGroup",
  },
  {
    name: "Vicinal dihalide",
    priority: 27.5,
    nomenclaturePriority: 21.5,
    confidence: "Medium",
    suffix: "Never suffix",
    prefix: "vic-dihalo",
    equivalentNames: ["1,2-dihalide", "vicinal dihalo compound"],
    smarts: "[CX4]([F,Cl,Br,I])[CX4]([F,Cl,Br,I])",
    displaySmarts: "[CX4]([F,Cl,Br,I])[CX4]([F,Cl,Br,I])",
    mcatNote:
      "Vicinal dihalides contain halogens on adjacent carbons. They are commonly formed by halogen addition to alkenes.",
    category: "functionalGroup",
  },
];