import type { ReactionRule } from "../reactionTypes";

const alkyneTrigger = { functionalGroups: ["Alkyne", "Terminal alkyne"] };

export const alkyneReactionRules: ReactionRule[] = [
  {
    id: "alkyne-hydrogenation",
    family: "alkynes",
    title: "Complete Hydrogenation",
    reagents: "H₂, Pt or Pd/C",
    reagentNote: "Full reduction",
    productHint: "Alkane",
    explanation: "Excess hydrogen with Pd/C fully reduces an alkyne to an alkane.",
    trigger: alkyneTrigger,
    transform: {
      type: "rdkitReactionSmarts",
      smarts: "[C:1]#[C:2]>>[C:1][C:2]",
    },
    priority: 300,
  },
  {
    id: "alkyne-lindlar-reduction",
    family: "alkynes",
    title: "Lindlar Reduction",
    reagents: "H₂, Lindlar catalyst",
    reagentNote: "Partial syn reduction",
    productHint: "Cis alkene",
    explanation: "Lindlar catalyst partially reduces an alkyne to a cis alkene.",
    trigger: alkyneTrigger,
    transform: {
      type: "rdkitReactionSmarts",
      smarts: "[C:1]#[C:2]>>[C:1]=[C:2]",
    },
    priority: 310,
  },
  {
    id: "alkyne-dissolving-metal-reduction",
    family: "alkynes",
    title: "Dissolving Metal Reduction",
    reagents: "Na, NH₃(l)",
    reagentNote: "Partial anti reduction",
    productHint: "Trans alkene",
    explanation: "Sodium in liquid ammonia partially reduces an alkyne to a trans alkene.",
    trigger: alkyneTrigger,
    transform: {
      type: "rdkitReactionSmarts",
      smarts: "[C:1]#[C:2]>>[C:1]=[C:2]",
    },
    priority: 320,
  },
  {
    id: "alkyne-hx-addition-one-equivalent",
    family: "alkynes",
    title: "HX Addition, 1 Equivalent",
    reagents: "1 equiv HBr or HCl",
    reagentNote: "Markovnikov hydrohalogenation",
    productHint: "Vinyl halide",
    explanation: "One equivalent of HX adds across an alkyne to form a vinyl halide.",
    trigger: alkyneTrigger,
    transform: {
      type: "rdkitReactionSmarts",
      smarts: "[C:1]#[C:2]>>[C:1]([Br])=[C:2]",
    },
    priority: 330,
  },
  {
    id: "alkyne-hx-addition-excess",
    family: "alkynes",
    title: "HX Addition, Excess",
    reagents: "excess HBr or HCl",
    reagentNote: "Double Markovnikov addition",
    productHint: "Geminal dihalide",
    explanation: "Excess HX adds twice to an alkyne to form a geminal dihalide.",
    trigger: alkyneTrigger,
    transform: {
      type: "rdkitReactionSmarts",
      smarts: "[C:1]#[C:2]>>[C:1]([Br])([Br])[C:2]",
    },
    priority: 340,
  },
  {
    id: "alkyne-halogenation-one-equivalent",
    family: "alkynes",
    title: "Halogenation, 1 Equivalent",
    reagents: "1 equiv Br₂ or Cl₂",
    reagentNote: "Anti addition",
    productHint: "Dihaloalkene",
    explanation: "One equivalent of halogen adds across an alkyne to form a dihaloalkene.",
    trigger: alkyneTrigger,
    transform: {
      type: "rdkitReactionSmarts",
      smarts: "[C:1]#[C:2]>>[C:1]([Br])=[C:2]([Br])",
    },
    priority: 350,
  },
  {
    id: "alkyne-halogenation-excess",
    family: "alkynes",
    title: "Halogenation, Excess",
    reagents: "excess Br₂ or Cl₂",
    reagentNote: "Full halogen addition",
    productHint: "Tetrahalide",
    explanation: "Excess halogen adds twice to an alkyne to form a tetrahalide.",
    trigger: alkyneTrigger,
    transform: {
      type: "rdkitReactionSmarts",
      smarts: "[C:1]#[C:2]>>[C:1]([Br])([Br])[C:2]([Br])([Br])",
    },
    priority: 360,
  },
  {
    id: "alkyne-acid-hydration",
    family: "alkynes",
    title: "Acid-Catalyzed Hydration",
    reagents: "HgSO₄, H₂SO₄, H₂O",
    reagentNote: "Markovnikov hydration",
    productHint: "Ketone",
    explanation: "Mercury-catalyzed hydration of an alkyne gives an enol that tautomerizes to a ketone.",
    trigger: alkyneTrigger,
    transform: {
      type: "rdkitReactionSmarts",
      smarts: "[C:1]#[C:2]>>[C:1](=O)[C:2]",
    },
    priority: 370,
  },
  {
    id: "alkyne-hydroboration-oxidation",
    family: "alkynes",
    title: "Hydroboration-Oxidation",
    reagents: "1) (Sia)₂BH or 9-BBN  2) H₂O₂, OH⁻",
    reagentNote: "Anti-Markovnikov hydration",
    productHint: "Aldehyde or ketone",
    explanation: "Hydroboration-oxidation gives anti-Markovnikov hydration; terminal alkynes produce aldehydes.",
    trigger: alkyneTrigger,
    transform: {
      type: "rdkitReactionSmarts",
      smarts: "[C:1]#[C:2]>>[C:1][C:2]=O",
    },
    priority: 380,
  },
  {
    id: "alkyne-oxidative-cleavage",
    family: "alkynes",
    title: "Oxidative Cleavage",
    reagents: "1) O₃  2) H₂O or KMnO₄",
    reagentNote: "Strong oxidative cleavage",
    productHint: "Carboxylic acids",
    explanation: "Oxidative cleavage breaks the alkyne into carboxylic acid products.",
    trigger: alkyneTrigger,
    transform: {
      type: "rdkitReactionSmarts",
      smarts: "[C:1]#[C:2]>>[C:1](=O)O.[C:2](=O)O",
    },
    priority: 390,
  },
  {
    id: "terminal-alkyne-alkylation",
    family: "alkynes",
    title: "Terminal Alkyne Alkylation",
    reagents: "1) NaNH₂  2) R-Br",
    reagentNote: "Acetylide formation then SN2",
    productHint: "Internal alkyne",
    explanation: "A terminal alkyne is deprotonated to an acetylide, which can attack a primary alkyl halide.",
    trigger: { functionalGroups: ["Terminal alkyne"] },
    transform: {
      type: "rdkitReactionSmarts",
      smarts: "[C:1]#[CH:2]>>[C:1]#[C:2]C",
    },
    priority: 400,
  },
];