import type { ReactionRule } from "../reactionTypes";

const alkyneTrigger = {
  anyFunctionalGroups: [
    "Alkyne",
    "Terminal alkyne",
    "Internal alkyne",
    "Cycloalkyne",
    "Enyne",
  ],
  includeSmarts: ["[C]#[C]"],
};

const terminalAlkyneTrigger = {
  anyFunctionalGroups: ["Terminal alkyne", "Alkyne", "Enyne"],
  includeSmarts: ["[C]#[CH]"],
};

const internalAlkyneTrigger = {
  anyFunctionalGroups: ["Internal alkyne", "Alkyne", "Cycloalkyne", "Enyne"],
  includeSmarts: ["[#6][C]#[C][#6]"],
};

export const alkyneReactionRules: ReactionRule[] = [
  {
    id: "alkyne-hydrogenation",
    family: "alkynes",
    reactionType: "reduction",
    title: "Complete Hydrogenation",
    reagents: "Excess H₂, Pt or Pd/C",
    reagentNote: "Full catalytic reduction",
    productHint: "Alkane",
    explanation:
      "Excess hydrogen over a metal catalyst reduces both pi bonds of an alkyne to give an alkane.",
    trigger: alkyneTrigger,
    transform: {
      type: "reactionSmarts",
      smarts: "[C:1]#[C:2]>>[C:1][C:2]",
    },
    mechanism: "Catalytic hydrogenation",
    priority: 300,
  },
  {
    id: "alkyne-lindlar-reduction",
    family: "alkynes",
    reactionType: "reduction",
    title: "Lindlar Reduction",
    reagents: "H₂, Lindlar catalyst",
    reagentNote: "Partial syn reduction",
    productHint: "Cis alkene",
    explanation:
      "A poisoned palladium catalyst stops reduction at the alkene and adds hydrogen syn, giving the cis alkene when E/Z geometry is possible.",
    trigger: alkyneTrigger,
    transform: {
      type: "reactionSmarts",
      smarts: "[C:1]#[C:2]>>[C:1]=[C:2]",
    },
    productStatus: "representative",
    mechanism: "Catalytic hydrogenation",
    selectivity: ["Syn addition", "Z alkene from an internal alkyne"],
    limitations: ["The current product SMILES does not yet encode the newly formed Z geometry."],
    priority: 310,
  },
  {
    id: "alkyne-dissolving-metal-reduction",
    family: "alkynes",
    reactionType: "reduction",
    title: "Dissolving-Metal Reduction",
    reagents: "Na or Li, NH₃(l)",
    reagentNote: "Partial anti reduction",
    productHint: "Trans alkene",
    explanation:
      "Single-electron transfer and protonation occur twice, producing anti addition and the trans alkene when E/Z geometry is possible.",
    trigger: alkyneTrigger,
    transform: {
      type: "reactionSmarts",
      smarts: "[C:1]#[C:2]>>[C:1]=[C:2]",
    },
    productStatus: "representative",
    mechanism: "Dissolving-metal reduction",
    selectivity: ["Anti addition", "E alkene from an internal alkyne"],
    limitations: ["The current product SMILES does not yet encode the newly formed E geometry."],
    priority: 320,
  },
  {
    id: "alkyne-hx-addition-one-equivalent",
    family: "alkynes",
    reactionType: "addition",
    title: "Hydrohalogenation: One Equivalent",
    reagents: "1 equiv HBr or HCl",
    reagentNote: "Markovnikov addition",
    productHint: "Vinyl halide",
    explanation:
      "One equivalent of HX adds across the triple bond to form a vinyl halide. Terminal alkynes usually place halogen on the internal carbon.",
    trigger: alkyneTrigger,
    transform: {
      type: "reactionSmarts",
      smarts: "[C:1]#[C:2]>>[C:1]([Br])=[C:2]",
      maxProducts: 4,
    },
    productStatus: "representative",
    mechanism: "Electrophilic addition",
    selectivity: ["Markovnikov for terminal alkynes", "E/Z mixtures may form"],
    priority: 330,
  },
  {
    id: "alkyne-hx-addition-excess",
    family: "alkynes",
    reactionType: "addition",
    title: "Hydrohalogenation: Excess HX",
    reagents: "Excess HBr or HCl",
    reagentNote: "Two Markovnikov additions",
    productHint: "Geminal dihalide",
    explanation:
      "Two equivalents of HX add to the alkyne, usually placing both halogens on the same carbon.",
    trigger: alkyneTrigger,
    transform: {
      type: "reactionSmarts",
      smarts: "[C:1]#[C:2]>>[C:1]([Br])([Br])[C:2]",
      maxProducts: 4,
    },
    productStatus: "representative",
    mechanism: "Electrophilic addition",
    selectivity: ["Geminal dihalide", "Markovnikov for terminal alkynes"],
    priority: 340,
  },
  {
    id: "alkyne-halogenation-one-equivalent",
    family: "alkynes",
    reactionType: "addition",
    title: "Halogenation: One Equivalent",
    reagents: "1 equiv Br₂ or Cl₂",
    reagentNote: "Predominantly anti addition",
    productHint: "Dihaloalkene",
    explanation:
      "One equivalent of halogen adds across one pi bond to form a vicinal dihaloalkene, commonly with trans geometry.",
    trigger: alkyneTrigger,
    transform: {
      type: "reactionSmarts",
      smarts: "[C:1]#[C:2]>>[C:1]([Br])=[C:2]([Br])",
    },
    productStatus: "representative",
    mechanism: "Electrophilic addition",
    selectivity: ["Predominantly anti addition"],
    limitations: ["The current product SMILES does not yet encode alkene geometry."],
    priority: 350,
  },
  {
    id: "alkyne-halogenation-excess",
    family: "alkynes",
    reactionType: "addition",
    title: "Halogenation: Excess",
    reagents: "Excess Br₂ or Cl₂",
    reagentNote: "Addition across both pi bonds",
    productHint: "Tetrahalide",
    explanation:
      "Two equivalents of halogen add across the triple bond to form a tetrahalide.",
    trigger: alkyneTrigger,
    transform: {
      type: "reactionSmarts",
      smarts: "[C:1]#[C:2]>>[C:1]([Br])([Br])[C:2]([Br])([Br])",
    },
    mechanism: "Electrophilic addition",
    priority: 360,
  },
  {
    id: "alkyne-acid-hydration",
    family: "alkynes",
    reactionType: "addition",
    title: "Mercury-Catalyzed Hydration of a Terminal Alkyne",
    reagents: "HgSO₄, H₂SO₄, H₂O",
    reagentNote: "Markovnikov hydration followed by tautomerization",
    productHint: "Methyl ketone",
    explanation:
      "A terminal alkyne forms a Markovnikov enol that tautomerizes to a methyl ketone.",
    trigger: terminalAlkyneTrigger,
    transform: {
      type: "reactionSmarts",
      smarts: "[C:1]#[CH:2]>>[C:1](=O)[CH3:2]",
    },
    mechanism: "Electrophilic hydration and keto-enol tautomerization",
    priority: 370,
  },
  {
    id: "alkyne-acid-hydration-internal",
    family: "alkynes",
    reactionType: "addition",
    title: "Mercury-Catalyzed Hydration of an Internal Alkyne",
    reagents: "HgSO₄, H₂SO₄, H₂O",
    reagentNote: "Hydration followed by tautomerization",
    productHint: "Ketone or ketone mixture",
    explanation:
      "Internal alkynes hydrate to enols that tautomerize to ketones. Unsymmetrical alkynes can produce constitutional isomers.",
    trigger: internalAlkyneTrigger,
    transform: {
      type: "reactionSmarts",
      smarts: "[C:1]#[C:2]>>[C:1](=O)[C:2]",
      maxProducts: 4,
    },
    productStatus: "representative",
    mechanism: "Electrophilic hydration and keto-enol tautomerization",
    limitations: ["Unsymmetrical internal alkynes may give a ketone mixture."],
    priority: 371,
  },
  {
    id: "alkyne-hydroboration-oxidation",
    family: "alkynes",
    reactionType: "oxidation",
    title: "Hydroboration–Oxidation of a Terminal Alkyne",
    reagents: "1) (Sia)₂BH or 9-BBN  2) H₂O₂, OH⁻",
    reagentNote: "Anti-Markovnikov hydration followed by tautomerization",
    productHint: "Aldehyde",
    explanation:
      "Bulky borane adds anti-Markovnikov to a terminal alkyne. Oxidation gives an enol that tautomerizes to an aldehyde.",
    trigger: terminalAlkyneTrigger,
    transform: {
      type: "reactionSmarts",
      smarts: "[C:1]#[CH:2]>>[C:1][CH:2]=O",
    },
    mechanism: "Hydroboration, oxidation, and tautomerization",
    selectivity: ["Anti-Markovnikov"],
    priority: 380,
  },
  {
    id: "alkyne-hydroboration-oxidation-internal",
    family: "alkynes",
    reactionType: "oxidation",
    title: "Hydroboration–Oxidation of an Internal Alkyne",
    reagents: "1) R₂BH  2) H₂O₂, OH⁻",
    reagentNote: "Hydration followed by tautomerization",
    productHint: "Ketone or ketone mixture",
    explanation:
      "Internal alkynes form ketones after hydroboration, oxidation, and tautomerization. Unsymmetrical substrates can give regioisomer mixtures.",
    trigger: internalAlkyneTrigger,
    transform: {
      type: "conceptOnly",
      reason:
        "An exact major product requires steric ranking of the two alkyne carbons and explicit borane selection.",
    },
    mechanism: "Hydroboration, oxidation, and tautomerization",
    priority: 381,
  },
  {
    id: "alkyne-cold-kmno4-oxidation",
    family: "alkynes",
    reactionType: "oxidation",
    title: "Cold Permanganate Oxidation of an Internal Alkyne",
    reagents: "KMnO4, H₂O, cold/dilute",
    reagentNote: "Mild oxidation",
    productHint: "1,2-Diketone",
    explanation:
      "Cold, dilute permanganate oxidizes an internal alkyne to a vicinal diketone without the vigorous cleavage associated with hot permanganate.",
    trigger: internalAlkyneTrigger,
    transform: {
      type: "reactionSmarts",
      smarts: "[C;H0:1]#[C;H0:2]>>[C:1](=O)[C:2](=O)",
    },
    productStatus: "computed",
    mechanism: "Mild permanganate oxidation",
    priority: 389,
  },
  {
    id: "alkyne-ozonolysis-cleavage",
    family: "alkynes",
    reactionType: "cleavage",
    title: "Alkyne Ozonolysis",
    reagents: "1) O₃  2) H₂O",
    reagentNote: "Oxidative cleavage",
    productHint: "Carboxylic acids; terminal carbon gives CO₂",
    explanation:
      "Ozonolysis cleaves an alkyne oxidatively. Internal alkyne carbons become carboxylic acids; a terminal alkyne carbon is ultimately oxidized to CO₂.",
    trigger: alkyneTrigger,
    transform: {
      type: "customHandler",
      handler: "oxidation",
      options: {
        mode: "alkyneOxidativeCleavage",
      },
    },
    productStatus: "computed",
    mechanism: "Oxidative cleavage",
    priority: 390,
  },
  {
    id: "alkyne-hot-kmno4-cleavage",
    family: "alkynes",
    reactionType: "cleavage",
    title: "Hot Permanganate Oxidative Cleavage",
    reagents: "1) KMnO4, OH⁻, heat  2) H₃O⁺",
    reagentNote: "Strong oxidative cleavage",
    productHint: "Carboxylic acids; terminal carbon gives CO₂",
    explanation:
      "Hot permanganate cleaves an alkyne. Internal alkyne carbons form carboxylic acids, while a terminal alkyne carbon is oxidized to CO₂.",
    trigger: alkyneTrigger,
    transform: {
      type: "customHandler",
      handler: "oxidation",
      options: {
        mode: "alkyneOxidativeCleavage",
      },
    },
    productStatus: "computed",
    mechanism: "Strong oxidative cleavage",
    priority: 391,
  },

  {
    id: "terminal-alkyne-deprotonation",
    family: "alkynes",
    reactionType: "acidBase",
    title: "Terminal Alkyne Deprotonation",
    reagents: "NaNH₂, liquid NH₃",
    reagentNote: "Formation of an acetylide ion",
    productHint: "Acetylide anion",
    explanation:
      "A terminal alkyne is acidic enough to be deprotonated by sodium amide, forming a carbon nucleophile.",
    trigger: terminalAlkyneTrigger,
    transform: {
      type: "reactionSmarts",
      smarts: "[C:1]#[CH:2]>>[C:1]#[C-:2]",
    },
    mechanism: "Proton transfer",
    priority: 400,
  },
  {
    id: "terminal-alkyne-alkylation",
    family: "alkynes",
    reactionType: "acidBase",
    title: "Terminal Alkyne Alkylation",
    reagents: "1) NaNH₂  2) methyl or primary R–X",
    reagentNote: "Acetylide formation followed by SN2",
    productHint: "Internal alkyne",
    explanation:
      "The acetylide ion attacks a methyl or primary alkyl halide, forming a new carbon-carbon bond.",
    trigger: terminalAlkyneTrigger,
    additionalReactants: [
      {
        label: "methyl or primary alkyl halide",
        trigger: {
          includeSmarts: ["[C;X4;H2,H3][Cl,Br,I]"],
        },
      },
    ],
    transform: {
      type: "reactionSmarts",
      smarts: "[C:1]#[CH:2].[C;X4:3][Cl,Br,I]>>[C:1]#[C:2]-[C:3]",
      maxProducts: 8,
    },
    mechanism: "Proton transfer followed by SN2",
    limitations: ["Secondary and tertiary alkyl halides favor elimination."],
    priority: 410,
  },
];
