import type { ReactionRule } from "../reactionTypes";

const aromaticTrigger = {
  anyFunctionalGroups: [
    "Benzene",
    "Alkylbenzene",
    "Toluene",
    "Phenol",
    "Aniline",
    "Anisole",
    "Nitrobenzene",
    "Aryl halide",
    "Naphthalene",
    "Anthracene",
    "Phenanthrene",
  ],
  includeSmarts: ["[cH]"],
};

const easModelNotes = {
  productStatus: "computed" as const,
  selectivityProfile: {
    mixture: "single" as const,
    majorProductOnly: true,
    sitePreference: "most-activated-aromatic-site" as const,
  },
  limitations: [
    "Simple benzene rings are ranked by ring activation/deactivation plus ortho/meta/para directing effects. Fused polycyclic aromatics intentionally fall back to unranked enumeration rather than applying simple-benzene directing constants outside their domain.",
  ],
};

export const aromaticReactionRules: ReactionRule[] = [
  {
    id: "aromatic-nitration",
    family: "aromatics",
    reactionType: "substitution",
    title: "Aromatic Nitration",
    reagents: "HNO₃, H₂SO₄",
    reagentNote: "Generates the nitronium electrophile",
    productHint: "Nitroarene",
    explanation:
      "The aromatic ring attacks NO₂⁺ and then loses a proton to restore aromaticity.",
    trigger: aromaticTrigger,
    transform: { type: "customHandler", handler: "substitution", options: { mode: "aromaticEas", electrophile: "nitro", maxProducts: 12 } },
    mechanism: "Electrophilic aromatic substitution",
    selectivity: [
      "Directing groups are classified from the atom directly bonded to the ring: resonance donors and alkyl/benzylic groups direct ortho/para; directly attached carbonyl, nitro, cyano, and sulfonyl groups direct meta; halogens are deactivating but ortho/para directing.",
      "When several benzene rings are present, ring activation/deactivation is ranked before positional preference; Ar–CH₂–C(=O)R is therefore not misclassified as a directly attached acyl meta director.",
      "For a monosubstituted alkyl/benzylic ring, para is preferred over ortho when steric effects distinguish them.",
    ],
    ...easModelNotes,
    priority: 1800,
  },
  {
    id: "aromatic-sulfonation",
    family: "aromatics",
    reactionType: "substitution",
    title: "Aromatic Sulfonation",
    reagents: "SO₃, H₂SO₄",
    reagentNote: "Reversible electrophilic substitution",
    productHint: "Arenesulfonic acid",
    explanation:
      "Sulfur trioxide electrophilically substitutes for an aromatic hydrogen. Hot dilute acid can reverse the reaction (desulfonation).",
    trigger: aromaticTrigger,
    transform: { type: "customHandler", handler: "substitution", options: { mode: "aromaticEas", electrophile: "sulfonic-acid", maxProducts: 12 } },
    mechanism: "Electrophilic aromatic substitution",
    selectivity: ["Reversible; temperature and acid concentration can control sulfonation versus desulfonation."],
    ...easModelNotes,
    priority: 1810,
  },
  {
    id: "aromatic-halogenation-bromination",
    family: "aromatics",
    reactionType: "substitution",
    title: "Aromatic Bromination",
    reagents: "Br₂, FeBr₃",
    reagentNote: "Lewis-acid-activated bromination",
    productHint: "Bromoarene",
    explanation:
      "FeBr₃ activates bromine, and the ring substitutes bromine for an aromatic hydrogen.",
    trigger: aromaticTrigger,
    transform: { type: "customHandler", handler: "substitution", options: { mode: "aromaticEas", electrophile: "bromo", maxProducts: 12 } },
    mechanism: "Electrophilic aromatic substitution",
    ...easModelNotes,
    priority: 1820,
  },
  {
    id: "aromatic-excess-bromination-phenol",
    family: "aromatics",
    reactionType: "substitution",
    title: "Excess Bromination of Phenol",
    reagents: "excess Br₂, H₂O",
    reagentNote: "Strongly activated ring; rapid 2,4,6-tribromination",
    productHint: "2,4,6-Tribromophenol",
    explanation:
      "Phenol is strongly activating and ortho/para-directing. With excess bromine, the two ortho positions and the para position are brominated rapidly, giving the 2,4,6-tribromo product when those positions are free.",
    trigger: {
      anyFunctionalGroups: ["Phenol"],
      includeSmarts: ["[OH][c]1[cH][cH][cH][cH][cH]1"],
    },
    transform: {
      type: "reactionSmarts",
      smarts:
        "[OH:7][c:1]1[cH:2][cH:3][cH:4][cH:5][cH:6]1>>[OH:7][c:1]1[c:2](Br)[cH:3][c:4](Br)[cH:5][c:6](Br)1",
      maxProducts: 4,
    },
    productStatus: "computed",
    mechanism: "Repeated electrophilic aromatic substitution",
    selectivityProfile: { mixture: "single", majorProductOnly: true },
    selectivity: ["OH directs bromination ortho/para; with all three sites free, 2,4,6-tribromination is the characteristic excess-Br₂ outcome."],
    limitations: ["If an ortho or para site is already substituted, the exact polybromination pattern must be ranked from the remaining available positions."],
    priority: 1821,
  },
  {
    id: "aromatic-excess-bromination-aniline",
    family: "aromatics",
    reactionType: "substitution",
    title: "Excess Bromination of Aniline",
    reagents: "excess Br₂, H₂O",
    reagentNote: "Strongly activated ring; rapid 2,4,6-tribromination",
    productHint: "2,4,6-Tribromoaniline",
    explanation:
      "Aniline is strongly activating and ortho/para-directing. In bromine water, excess bromine commonly substitutes at both ortho positions and the para position when they are available.",
    trigger: {
      anyFunctionalGroups: ["Aniline"],
      includeSmarts: ["[NH2][c]1[cH][cH][cH][cH][cH]1"],
    },
    transform: {
      type: "reactionSmarts",
      smarts:
        "[NH2:7][c:1]1[cH:2][cH:3][cH:4][cH:5][cH:6]1>>[NH2:7][c:1]1[c:2](Br)[cH:3][c:4](Br)[cH:5][c:6](Br)1",
      maxProducts: 4,
    },
    productStatus: "computed",
    mechanism: "Repeated electrophilic aromatic substitution",
    selectivityProfile: { mixture: "single", majorProductOnly: true },
    selectivity: ["NH₂ directs bromination ortho/para; with all three sites free, 2,4,6-tribromination is the characteristic excess-Br₂ outcome."],
    limitations: ["Protected or protonated amines have different directing strength and may not undergo this rapid tribromination pattern."],
    priority: 1822,
  },
  {
    id: "aromatic-excess-bromination-general",
    family: "aromatics",
    reactionType: "substitution",
    title: "Aromatic Polybromination with Excess Br₂",
    reagents: "excess Br₂, FeBr₃",
    reagentNote: "Further EAS is possible under excess/forcing bromination conditions",
    productHint: "Polybrominated arene",
    explanation:
      "Excess bromine can drive more than one electrophilic aromatic substitution when the ring remains sufficiently reactive. The exact number and positions of bromines depend on the substituents already present and on how each newly installed bromine changes ring reactivity.",
    trigger: {
      ...aromaticTrigger,
      excludedFunctionalGroups: ["Phenol", "Aniline"],
    },
    transform: {
      type: "conceptOnly",
      reason:
        "A general excess-Br₂ product cannot be represented as one universal structure: each substitution changes the directing/deactivating pattern. PocketChem computes the standard 2,4,6 products for unsubstituted phenol and aniline separately and keeps this broader case as an explicit polybromination possibility.",
    },
    mechanism: "Repeated electrophilic aromatic substitution",
    limitations: ["Ordinary bromination is usually stopped at monobromination unless excess reagent and sufficient ring activation/forcing conditions are present."],
    priority: 1825,
  },
  {
    id: "aromatic-halogenation-chlorination",
    family: "aromatics",
    reactionType: "substitution",
    title: "Aromatic Chlorination",
    reagents: "Cl₂, FeCl₃",
    reagentNote: "Lewis-acid-activated chlorination",
    productHint: "Chloroarene",
    explanation:
      "FeCl₃ activates chlorine, and the ring substitutes chlorine for an aromatic hydrogen.",
    trigger: aromaticTrigger,
    transform: { type: "customHandler", handler: "substitution", options: { mode: "aromaticEas", electrophile: "chloro", maxProducts: 12 } },
    mechanism: "Electrophilic aromatic substitution",
    ...easModelNotes,
    priority: 1830,
  },
  {
    id: "aromatic-halogenation-iodination",
    family: "aromatics",
    reactionType: "substitution",
    title: "Aromatic Iodination",
    reagents: "I₂, oxidizing agent (for example HNO₃ or H₂O₂)",
    reagentNote: "Oxidative generation of an electrophilic iodine species",
    productHint: "Iodoarene",
    explanation:
      "Iodination is an electrophilic aromatic substitution, but I₂ normally needs an oxidizing agent to generate a sufficiently reactive iodine electrophile.",
    trigger: aromaticTrigger,
    transform: { type: "customHandler", handler: "substitution", options: { mode: "aromaticEas", electrophile: "iodo", maxProducts: 12 } },
    mechanism: "Electrophilic aromatic substitution",
    ...easModelNotes,
    priority: 1831,
  },
  {
    id: "aromatic-halogenation-fluorination",
    family: "aromatics",
    reactionType: "substitution",
    title: "Controlled Aromatic Fluorination",
    reagents: "F-TEDA-BF₄ (Selectfluor) or another controlled electrophilic fluorinating reagent",
    reagentNote: "Direct F₂ is too reactive for ordinary selective EAS",
    productHint: "Fluoroarene",
    explanation:
      "Controlled electrophilic fluorinating reagents can install fluorine by aromatic substitution without the uncontrolled reactivity of elemental fluorine.",
    trigger: aromaticTrigger,
    transform: { type: "customHandler", handler: "substitution", options: { mode: "aromaticEas", electrophile: "fluoro", maxProducts: 12 } },
    mechanism: "Electrophilic aromatic substitution",
    ...easModelNotes,
    priority: 1832,
  },
  {
    id: "aromatic-desulfonation",
    family: "aromatics",
    reactionType: "substitution",
    title: "Aromatic Desulfonation",
    reagents: "dilute H₂SO₄/H₂O, heat (steam)",
    reagentNote: "Reverse of aromatic sulfonation",
    productHint: "Arene",
    explanation:
      "Arenesulfonation is reversible. Heating an arenesulfonic acid in aqueous acid removes SO₃H and restores the aromatic C–H bond.",
    trigger: { includeSmarts: ["[c][S](=O)(=O)O"] },
    transform: { type: "reactionSmarts", smarts: "[c:1][S:2](=[O:3])(=[O:4])[O:5]>>[cH:1]" },
    productStatus: "computed",
    mechanism: "Reverse electrophilic aromatic substitution",
    priority: 1833,
  },
  {
    id: "aromatic-gattermann-koch-benzene",
    family: "aromatics",
    reactionType: "substitution",
    title: "Gattermann–Koch Formylation",
    reagents: "CO, HCl, AlCl₃ (often CuCl)",
    reagentNote: "Electrophilic aromatic formylation",
    productHint: "Aromatic aldehyde",
    explanation:
      "CO and HCl under Lewis-acid catalysis generate a formylating electrophile. Benzene gives benzaldehyde by electrophilic aromatic substitution.",
    trigger: {
      includeSmarts: ["[cH]1[cH][cH][cH][cH][cH]1"],
    },
    transform: {
      type: "reactionSmarts",
      smarts: "[cH:1]>>[c:1][CH]=O",
      maxProducts: 6,
    },
    productStatus: "computed",
    mechanism: "Electrophilic aromatic substitution",
    selectivityProfile: { mixture: "single", majorProductOnly: true },
    limitations: ["Strongly deactivated rings do not undergo Gattermann–Koch formylation readily."],
    priority: 1835,
  },
  {
    id: "aromatic-gattermann-koch-alkylbenzene",
    family: "aromatics",
    reactionType: "substitution",
    title: "Gattermann–Koch Formylation of an Alkylbenzene",
    reagents: "CO, HCl, AlCl₃ (often CuCl)",
    reagentNote: "Para formylation is usually favored for a simple monosubstituted alkylbenzene",
    productHint: "para-Alkylbenzaldehyde",
    explanation:
      "An alkyl substituent activates the ring and directs electrophilic formylation ortho/para. For a simple monosubstituted alkylbenzene, the para product is normally favored because it avoids ortho steric crowding; the ortho product can be minor.",
    trigger: {
      includeSmarts: ["[cH]1[cH][cH][c]([C;X4])[cH][cH]1"],
    },
    transform: {
      type: "reactionSmarts",
      smarts:
        "[cH:1]1[cH:2][cH:3][c:4]([C;X4:8])[cH:5][cH:6]1>>[c:1]1([CH]=O)[cH:2][cH:3][c:4]([C:8])[cH:5][cH:6]1",
      maxProducts: 6,
    },
    productStatus: "computed",
    mechanism: "Electrophilic aromatic substitution",
    selectivityProfile: { mixture: "single", majorProductOnly: true },
    selectivity: ["Alkyl groups are ortho/para directors; the less hindered para formylation product is used as the major representative for a simple monosubstituted alkylbenzene."],
    limitations: ["More highly substituted arenes require full directing-group competition rather than this monosubstituted-ring rule."],
    priority: 1836,
  },
  {
    id: "aromatic-friedel-crafts-alkylation",
    family: "aromatics",
    reactionType: "substitution",
    title: "Friedel–Crafts Alkylation",
    reagents: "AlCl₃",
    reagentNote: "Draw the arene and alkyl halide as disconnected structures",
    productHint: "Alkylbenzene",
    explanation:
      "An alkyl electrophile substitutes onto an activated aromatic ring. Carbocation rearrangement and polyalkylation are common complications.",
    trigger: aromaticTrigger,
    additionalReactants: [
      {
        label: "alkyl chloride, bromide, or iodide",
        trigger: { includeSmarts: ["[C;X4][Cl,Br,I]"] },
      },
    ],
    transform: {
      type: "reactionSmarts",
      smarts: "[cH:1].[C;X4:2][Cl,Br,I]>>[c:1]-[C:2]",
      maxProducts: 12,
    },
    productStatus: "representative",
    mechanism: "Electrophilic aromatic substitution",
    limitations: [
      "The engine enumerates available aromatic C-H sites but does not rank ortho/para/meta directing effects.",
      "Fails on strongly deactivated rings.",
      "Amino groups complex strongly with AlCl₃ unless protected.",
      "Carbocation rearrangement and polyalkylation may occur; the generated structure represents direct attachment of the drawn alkyl group.",
    ],
    constraints: [
      "friedel-crafts-ring-not-strongly-deactivated",
      "friedel-crafts-amine-compatible",
    ],
    priority: 1840,
  },
  {
    id: "aromatic-friedel-crafts-acylation",
    family: "aromatics",
    reactionType: "substitution",
    title: "Friedel–Crafts Acylation",
    reagents: "AlCl₃",
    reagentNote: "Draw the arene and acyl chloride as disconnected structures",
    productHint: "Aryl ketone",
    explanation:
      "An acylium ion substitutes onto an activated aromatic ring to form an aryl ketone. The acylium ion does not normally rearrange.",
    trigger: aromaticTrigger,
    additionalReactants: [
      {
        label: "acyl chloride",
        trigger: { includeSmarts: ["[C](=O)[Cl,Br]"] },
      },
    ],
    transform: {
      type: "reactionSmarts",
      smarts: "[cH:1].[C:2](=[O:3])[Cl,Br]>>[c:1]-[C:2](=[O:3])",
      maxProducts: 12,
    },
    productStatus: "representative",
    mechanism: "Electrophilic aromatic substitution",
    limitations: ["The engine enumerates available aromatic C-H sites but does not rank ortho/para/meta directing effects.", "Fails on strongly deactivated rings and often on unprotected amino-substituted rings."],
    constraints: [
      "friedel-crafts-ring-not-strongly-deactivated",
      "friedel-crafts-amine-compatible",
    ],
    priority: 1850,
  },
  {
    id: "aromatic-catalytic-hydrogenation",
    family: "aromatics",
    reactionType: "reduction",
    title: "Aromatic Ring Hydrogenation",
    reagents: "H₂, Pt/Pd/Ni, high pressure and heat",
    reagentNote: "Forcing catalytic reduction",
    productHint: "Saturated cyclohexane derivative",
    explanation:
      "Under forcing conditions, an aromatic ring can be fully hydrogenated to the corresponding saturated ring.",
    trigger: aromaticTrigger,
    transform: {
      type: "reactionSmarts",
      smarts: "[c:1]1[c:2][c:3][c:4][c:5][c:6]1>>[C:1]1-[C:2]-[C:3]-[C:4]-[C:5]-[C:6]-1",
      maxProducts: 8,
    },
    productStatus: "computed",
    mechanism: "Heterogeneous catalytic hydrogenation",
    limitations: ["For fused polycyclic aromatic systems, multiple rings may require repeated/forcing hydrogenation and are not collapsed into one assumed global product."],
    priority: 1860,
  },
  {
    id: "aromatic-birch-reduction",
    family: "aromatics",
    reactionType: "acidBase",
    title: "Birch Reduction",
    reagents: "Na or Li, NH₃(l), ROH",
    reagentNote: "Dissolving-metal partial reduction",
    productHint: "1,4-Cyclohexadiene derivative",
    explanation:
      "A Birch reduction converts an aromatic ring into a nonconjugated 1,4-cyclohexadiene. Substituents control which ring carbons are reduced.",
    trigger: aromaticTrigger,
    transform: {
      type: "customHandler",
      handler: "reduction",
      options: { mode: "birchReduction" },
    },
    productStatus: "computed",
    mechanism: "Stepwise electron–proton transfer",
    selectivity: [
      "The ring is reduced to a nonconjugated 1,4-cyclohexadiene.",
      "A directly attached pi-accepting EWG (for example C=O or CN) favors an ipso-saturated product; an alkyl, alkoxy, or amino donor favors a product with the substituted ipso carbon remaining vinylic.",
      "Na/NH₃/ROH is Birch reduction; NaNH₂/NH₃ is a different benzyne-forming condition.",
    ],
    limitations: ["Highly fused polycyclic aromatics and rings with several strongly competing substituents may require a more detailed electronic model."],
    priority: 1865,
  },
  {
    id: "benzylic-bromination",
    family: "aromatics",
    reactionType: "radical",
    title: "Benzylic Bromination",
    reagents: "NBS, hν or radical initiator",
    reagentNote: "Selective radical substitution",
    productHint: "Benzylic bromide",
    explanation:
      "NBS maintains a low bromine concentration and substitutes a benzylic hydrogen through a resonance-stabilized radical.",
    trigger: {
      // Structural benzylic matching also covers fused systems such as
      // 2,3-dihydrobenzofuran; requiring the high-level "Alkylbenzene" label
      // caused those legitimate benzylic sites to be missed.
      includeSmarts: ["[c][C;H1,H2,H3]"],
    },
    transform: {
      type: "reactionSmarts",
      smarts: "[c:1][C;H1,H2,H3:2]>>[c:1][C:2]Br",
      maxProducts: 8,
    },
    mechanism: "Radical-chain substitution",
    selectivity: ["Occurs at a benzylic carbon bearing at least one hydrogen."],
    productStatus: "representative",
    limitations: ["Multiple nonequivalent benzylic sites can give multiple products; stereochemical outcomes are not ranked."],
    constraints: ["benzylic-radical-halogenation-needs-h"],
    priority: 1870,
  },
  {
    id: "benzylic-oxidation",
    family: "aromatics",
    reactionType: "oxidation",
    title: "Benzylic Side-Chain Oxidation",
    reagents: "1) KMnO4, OH⁻, heat  2) H₃O⁺",
    reagentNote: "Requires at least one benzylic hydrogen",
    productHint: "Aromatic carboxylic acid",
    explanation:
      "Strong oxidation converts an alkyl side chain containing a benzylic hydrogen into a carboxylic acid, regardless of the original side-chain length.",
    trigger: {
      includeSmarts: ["[c][C;H1,H2,H3]"],
    },
    transform: {
      type: "customHandler",
      handler: "oxidation",
      options: { mode: "benzylicSideChainOxidation" },
    },
    productStatus: "computed",
    mechanism: "Strong benzylic oxidation",
    constraints: ["benzylic-oxidation-needs-h"],
    priority: 1880,
  },
  {
    id: "nitroarene-reduction",
    family: "aromatics",
    reactionType: "reduction",
    title: "Nitro Group Reduction",
    reagents: "H₂, Pd/C; or Fe/HCl; or Sn/HCl",
    reagentNote: "Nitro-to-amine reduction",
    productHint: "Aryl amine",
    explanation:
      "A nitro substituent can be reduced to an amino group without hydrogenating the aromatic ring under suitable conditions.",
    trigger: {
      anyFunctionalGroups: ["Nitrobenzene"],
      includeSmarts: ["[c][N+](=O)[O-]"],
    },
    transform: {
      type: "reactionSmarts",
      smarts: "[c:1][N+:2](=[O:3])[O-:4]>>[c:1][NH2+0:2]",
    },
    mechanism: "Multi-step reduction",
    priority: 1890,
  },
  ...([
    {
      slug: "azide",
      title: "Nucleophilic Aromatic Substitution with Azide",
      reagents: "1 equiv NaN₃, heat as needed",
      product: "Aryl azide",
    },
    {
      slug: "cyanide",
      title: "Nucleophilic Aromatic Substitution with Cyanide",
      reagents: "NaCN or KCN, heat as needed",
      product: "Aryl nitrile",
    },
    {
      slug: "hydroxide",
      title: "Nucleophilic Aromatic Substitution with Hydroxide",
      reagents: "NaOH, heat",
      product: "Phenol",
    },
    {
      slug: "amino",
      title: "Nucleophilic Aromatic Substitution with Amide/Ammonia",
      reagents: "NH₂⁻ or NH₃ under suitable SNAr conditions",
      product: "Aryl amine",
    },
    {
      slug: "methoxide",
      title: "Nucleophilic Aromatic Substitution with Methoxide",
      reagents: "NaOCH₃, CH₃OH",
      product: "Aryl methyl ether",
    },
  ] as const).map(({ slug, title, reagents, product }, index) => ({
    id: `aryl-halide-snar-${slug}`,
    family: "aromatics" as const,
    reactionType: "substitution" as const,
    title,
    reagents,
    reagentNote: "Addition–elimination requires a strong EWG ortho or para to the leaving group",
    productHint: product,
    explanation:
      "A strong electron-withdrawing group such as NO₂, a carbonyl group, CN, or SO₂R ortho or para to an aryl halide stabilizes the Meisenheimer intermediate, allowing nucleophilic aromatic substitution.",
    trigger: {
      anyFunctionalGroups: ["Aryl halide"],
      includeSmarts: ["[c][F,Cl,Br,I]"],
    },
    transform: {
      type: "customHandler" as const,
      handler: "substitution" as const,
      options: { mode: "aromaticSnAr", nucleophile: slug },
    },
    productStatus: "computed" as const,
    mechanism: "SNAr addition–elimination",
    selectivity: [
      "Activation is positional: the EWG must be ortho or para to the leaving group; a meta-only EWG does not provide the same resonance stabilization.",
      "If several aryl halides are present, only structurally activated leaving-group sites are transformed.",
    ],
    priority: 1900 + index,
  })),
  {
    id: "aryl-halide-benzyne-amination",
    family: "aromatics",
    reactionType: "substitution",
    title: "Benzyne Amination of an Aryl Halide",
    reagents: "NaNH₂, NH₃(l)",
    reagentNote: "Elimination–addition through a benzyne intermediate",
    productHint: "Aryl amine (regioisomer mixture possible)",
    explanation:
      "Strong base removes an ortho hydrogen while halide leaves to form benzyne. Amide then adds to either carbon of the benzyne, so substituted substrates can give ipso and cine products.",
    trigger: { includeSmarts: ["[c]([F,Cl,Br,I])[cH]"] },
    transform: {
      type: "customHandler",
      handler: "substitution",
      options: { mode: "aromaticBenzyneAmination" },
    },
    productStatus: "computed",
    mechanism: "Benzyne elimination–addition",
    selectivityProfile: { mixture: "possible" },
    selectivity: ["Requires an ortho hydrogen next to the aryl halide.", "Do not confuse NaNH₂/NH₃ with Na/NH₃/ROH Birch reduction."],
    priority: 1910,
  },
];
