import type { ReactionRule } from "../reactionTypes";
import { GRIGNARD_OR_ORGANOLITHIUM_TRIGGER_SMARTS } from "../organometallic";

const carboxylicAcidTrigger = {
  anyFunctionalGroups: [
    "Carboxylic acid",
    "Benzoic acid",
    "Enoic acid",
    "Cinnamic acid",
    "Crotonic acid",
    "Acrylic acid",
  ],
  includeSmarts: ["[CX3](=O)[OX2H1]"],
};

export const carboxylicAcidReactionRules: ReactionRule[] = [
  {
    id: "carboxylic-acid-deprotonation",
    family: "carboxylic-acids",
    reactionType: "acidBase",
    title: "Carboxylic Acid Deprotonation",
    reagents: "NaOH, NaHCO₃, or another base",
    reagentNote: "Acid–base reaction",
    productHint: "Carboxylate salt",
    explanation:
      "A base removes the acidic O–H proton to form a resonance-stabilized carboxylate.",
    trigger: carboxylicAcidTrigger,
    transform: {
      type: "reactionSmarts",
      smarts: "[C:1](=[O:2])[OH:3]>>[C:1](=[O:2])[O-:3]",
    },
    mechanism: "Proton transfer",
    priority: 1290,
  },
  {
    id: "carboxylic-acid-lah-reduction",
    family: "carboxylic-acids",
    reactionType: "reduction",
    title: "LiAlH₄ Reduction",
    reagents: "1) LiAlH₄  2) H₃O⁺",
    reagentNote: "Strong hydride reduction",
    productHint: "Primary alcohol",
    explanation:
      "LiAlH₄ reduces a carboxylic acid carbonyl carbon to a primary alcohol. NaBH₄ is normally too weak.",
    trigger: carboxylicAcidTrigger,
    transform: {
      type: "customHandler",
      handler: "reduction",
      options: {
        mode: "oneTwoAddition",
        substrateClass: "carboxylic-acid",
        nucleophile: "hydride",
        reagents: ["LiAlH4"],
      },
    },
    mechanism: "Hydride reduction",
    priority: 1300,
  },
  {
    id: "carboxylic-acid-borane-reduction",
    family: "carboxylic-acids",
    reactionType: "reduction",
    title: "Borane Reduction",
    reagents: "1) BH₃·THF  2) H₂O",
    reagentNote: "Chemoselective carboxylic-acid reduction",
    productHint: "Primary alcohol",
    explanation:
      "Borane rapidly reduces carboxylic acids to primary alcohols and can be more selective than LiAlH₄ in multifunctional molecules.",
    trigger: carboxylicAcidTrigger,
    transform: {
      type: "reactionSmarts",
      smarts: "[C:1](=[O:2])[OH:3]>>[CH2:1][OH:2]",
    },
    mechanism: "Hydride reduction",
    selectivity: ["Often selectively reduces CO₂H in the presence of other carbonyl derivatives."],
    priority: 1305,
  },
  {
    id: "carboxylic-acid-fischer-esterification",
    family: "carboxylic-acids",
    reactionType: "substitution",
    title: "Fischer Esterification",
    reagents: "ROH, catalytic H₂SO₄, heat",
    reagentNote: "Equilibrium esterification",
    productHint: "Ester",
    explanation:
      "A carboxylic acid and an alcohol form an ester under acid catalysis. Removing water or using excess alcohol drives the equilibrium toward product.",
    trigger: carboxylicAcidTrigger,
    transform: {
      type: "conceptOnly",
      reason: "The alcohol reactant must be specified before an exact ester can be generated.",
    },
    mechanism: "Nucleophilic acyl substitution",
    limitations: ["Reversible; the equilibrium must be driven toward the ester."],
    priority: 1310,
  },
  {
    id: "carboxylic-acid-to-acid-chloride",
    family: "carboxylic-acids",
    reactionType: "substitution",
    title: "Acid Chloride Formation",
    reagents: "SOCl₂, (COCl)₂, or PCl₅",
    reagentNote: "Activates the carboxylic acid",
    productHint: "Acid chloride",
    explanation:
      "Thionyl chloride, oxalyl chloride, or phosphorus chlorides replace the acid hydroxyl group with chlorine.",
    trigger: carboxylicAcidTrigger,
    transform: {
      type: "reactionSmarts",
      smarts: "[C:1](=[O:2])[OH:3]>>[C:1](=[O:2])Cl",
    },
    mechanism: "Nucleophilic acyl substitution",
    priority: 1320,
  },
  {
    id: "carboxylic-acid-thermal-amidation-ammonia",
    family: "carboxylic-acids",
    reactionType: "substitution",
    title: "Thermal Amide Formation with Ammonia",
    reagents: "NH₃, heat",
    reagentNote: "Ammonium carboxylate formation followed by dehydration",
    productHint: "Primary amide",
    explanation:
      "A carboxylic acid reacts with ammonia to form an ammonium carboxylate; sufficiently strong heating removes water to give the corresponding primary amide. This provides the standard first step of a carboxylic-acid → amide → nitrile sequence.",
    trigger: carboxylicAcidTrigger,
    additionalReactants: [
      {
        id: "ammonia",
        label: "ammonia",
        trigger: { includeSmarts: ["[NH3]"] },
        supplyMode: "auto",
        presetSmiles: "N",
        contributesToProduct: true,
        role: "nucleophile",
        searchAliases: ["NH3", "NH₃", "ammonia"],
      },
    ],
    transform: {
      type: "reactionSmarts",
      smarts: "[C:1](=[O:2])[OH:3].[NH3:4]>>[C:1](=[O:2])[NH2:4]",
      maxProducts: 8,
    },
    productStatus: "computed",
    mechanism: "Ammonium carboxylate formation followed by thermal dehydration",
    limitations: [
      "Direct amidation generally requires substantial heating; activated-acid methods are preferred for many sensitive or substituted amines.",
    ],
    searchAliases: ["NH3 heat amide", "ammonia heat", "carboxylic acid to primary amide"],
    priority: 1328,
  },
  {
    id: "carboxylic-acid-to-nitrile-via-amide",
    family: "carboxylic-acids",
    reactionType: "elimination",
    title: "Carboxylic Acid to Nitrile",
    reagents: "1) NH₃, heat  2) POCl₃",
    reagentNote: "Primary amide formation followed by dehydration",
    productHint: "Nitrile",
    explanation:
      "Ammonia and heat first convert the carboxylic acid into the corresponding primary amide. POCl₃ then dehydrates that amide to a nitrile, retaining the original carboxyl carbon as the nitrile carbon.",
    trigger: carboxylicAcidTrigger,
    transform: {
      type: "reactionSmarts",
      smarts: "[C:1](=[O:2])[OH:3]>>[C:1]#N",
      maxProducts: 8,
    },
    productStatus: "computed",
    mechanism: "Thermal amidation followed by dehydrative conversion of the primary amide to a nitrile",
    selectivity: [
      "The carboxyl carbon is retained and becomes the nitrile carbon.",
      "The NH₃/heat step forms the primary amide intermediate; POCl₃ performs the dehydration.",
    ],
    searchAliases: [
      "NH3 heat POCl3",
      "NH₃ heat POCl₃",
      "carboxylic acid to nitrile",
      "acid to nitrile via amide",
      "primary amide dehydration sequence",
    ],
    priority: 1329,
  },
  {
    id: "carboxylic-acid-amide-formation",
    family: "carboxylic-acids",
    reactionType: "substitution",
    title: "Amide Formation",
    reagents: "1) SOCl₂  2) NH₃ or RNH₂",
    reagentNote: "Activation followed by aminolysis",
    productHint: "Amide",
    explanation:
      "The acid is first converted into a more reactive derivative, commonly an acid chloride, and then treated with ammonia or an amine.",
    trigger: carboxylicAcidTrigger,
    additionalReactants: [
      {
        label: "ammonia, primary amine, or secondary amine",
        trigger: { includeSmarts: ["[N;H1,H2,H3;!$(N[C,S,P]=O)]"] },
      },
    ],
    transform: {
      type: "reactionSmarts",
      smarts: "[C:1](=[O:2])[OH:3].[N;H1,H2,H3:4]>>[C:1](=[O:2])[N:4]",
      maxProducts: 8,
    },
    mechanism: "Nucleophilic acyl substitution",
    priority: 1330,
  },
  {
    id: "carboxylic-acid-coupling-reagent-amidation",
    family: "carboxylic-acids",
    reactionType: "substitution",
    title: "Coupling-Reagent Amidation",
    reagents: "RNH₂, DCC or EDC (often with DMAP/HOBt)",
    reagentNote: "Direct activated coupling",
    productHint: "Amide",
    explanation:
      "A carbodiimide or related coupling reagent activates the carboxylic acid so an amine can form an amide under comparatively mild conditions.",
    trigger: carboxylicAcidTrigger,
    additionalReactants: [
      {
        label: "ammonia, primary amine, or secondary amine",
        trigger: { includeSmarts: ["[N;H1,H2,H3;!$(N[C,S,P]=O)]"] },
      },
    ],
    transform: {
      type: "reactionSmarts",
      smarts: "[C:1](=[O:2])[OH:3].[N;H1,H2,H3:4]>>[C:1](=[O:2])[N:4]",
      maxProducts: 8,
    },
    course: "advanced",
    mechanism: "Activated acyl substitution",
    priority: 1335,
  },
  {
    id: "carboxylic-acid-curtius-rearrangement",
    family: "carboxylic-acids",
    reactionType: "rearrangement",
    title: "Curtius Rearrangement to a Primary Amine",
    reagents: "1) convert acid to acyl azide (for example DPPA or SOCl₂/NaN₃)  2) heat  3) H₂O",
    reagentNote: "Acyl azide → isocyanate → amine",
    productHint: "Primary amine with one fewer carbon",
    explanation:
      "An acyl azide loses N₂ and rearranges to an isocyanate. Hydrolysis and decarboxylation give a primary amine in which the original carbonyl carbon has been removed.",
    trigger: { ...carboxylicAcidTrigger, includeSmarts: ["[#6][CX3](=O)[OX2H1]"] },
    transform: {
      type: "reactionSmarts",
      smarts: "[#6:1][C:2](=[O:3])[OH:4]>>[#6:1][NH2]",
      maxProducts: 8,
    },
    productStatus: "computed",
    mechanism: "1,2-migration in an acyl nitrene equivalent followed by isocyanate hydrolysis",
    priority: 1338,
  },
  {
    id: "beta-keto-acid-decarboxylation",
    family: "carboxylic-acids",
    reactionType: "cleavage",
    title: "β-Keto Acid Decarboxylation",
    reagents: "heat",
    reagentNote: "Six-membered cyclic transition state",
    productHint: "Ketone after loss of CO₂",
    explanation:
      "A β-keto acid readily loses carbon dioxide on heating, initially giving an enol that tautomerizes to a ketone.",
    trigger: {
      ...carboxylicAcidTrigger,
      includeSmarts: ["[CX3](=O)[CX4H1,CX4H2][CX3](=O)[OX2H1]"],
    },
    transform: {
      type: "conceptOnly",
      reason: "The decarboxylation product requires atom-preserving removal of CO₂ followed by enol–keto tautomerization.",
    },
    mechanism: "Thermal decarboxylation",
    priority: 1340,
  },
  {
    id: "malonic-acid-derivative-decarboxylation",
    family: "carboxylic-acids",
    reactionType: "cleavage",
    title: "Malonic Acid Derivative Decarboxylation",
    reagents: "H₃O⁺, heat",
    reagentNote: "Hydrolysis followed by CO₂ loss",
    productHint: "Substituted carboxylic acid",
    explanation:
      "A malonic ester synthesis ends with ester hydrolysis and thermal decarboxylation to give a substituted acetic-acid derivative.",
    trigger: {
      ...carboxylicAcidTrigger,
      includeSmarts: ["[CX3](=O)([OX2H1])[CX4H1,CX4H2][CX3](=O)[OX2H1]"],
    },
    transform: {
      type: "conceptOnly",
      reason: "This pathway is shown only when a complete malonic-acid derivative can be recognized from the drawn reactant.",
    },
    mechanism: "Thermal decarboxylation",
    limitations: ["Normally encountered as the final step of a malonic ester synthesis."],
    priority: 1342,
  },
  {
    id: "carboxylic-acid-alpha-halogenation-hvz",
    family: "carboxylic-acids",
    reactionType: "substitution",
    title: "Hell–Volhard–Zelinsky Reaction",
    reagents: "1) Br₂, PBr₃  2) H₂O",
    reagentNote: "α-Bromination of a carboxylic acid",
    productHint: "α-Bromo carboxylic acid",
    explanation:
      "A carboxylic acid containing at least one alpha hydrogen is converted to its acid bromide, enolized, brominated at the alpha carbon, and hydrolyzed back to the acid.",
    trigger: {
      ...carboxylicAcidTrigger,
      includeSmarts: ["[C;H1,H2,H3][CX3](=O)[OX2H1]"],
    },
    transform: {
      type: "reactionSmarts",
      smarts: "[C;H1,H2,H3:1][C:2](=[O:3])[OH:4]>>[C:1]([Br])[C:2](=[O:3])[OH:4]",
      maxProducts: 8,
    },
    mechanism: "Enol halogenation",
    selectivity: ["Bromination occurs at an alpha carbon bearing hydrogen."],
    productStatus: "representative",
    limitations: ["Unsymmetrical acids can generate more than one alpha-brominated constitutional product."],
    priority: 1350,
  },
  {
    id: "organometallic-carboxylation",
    family: "carboxylic-acids",
    reactionType: "coupling",
    title: "Grignard or Organolithium Carboxylation",
    reagents: "1) CO₂  2) H₃O⁺",
    reagentNote: "Draw the organometallic reagent and carbon dioxide as disconnected structures",
    productHint: "Carboxylic acid",
    explanation:
      "A Grignard or organolithium carbon nucleophile attacks carbon dioxide, adding one carbon to the carbon skeleton; acidic workup gives a carboxylic acid.",
    trigger: { includeSmarts: [GRIGNARD_OR_ORGANOLITHIUM_TRIGGER_SMARTS] },
    additionalReactants: [
      { label: "carbon dioxide", trigger: { includeSmarts: ["O=C=O"] } },
    ],
    transform: {
      type: "reactionSmarts",
      smarts: "[#6:1][Mg,Li].[O:2]=[C:3]=[O:4]>>[#6:1][C:3](=[O:2])[OH:4]",
      maxProducts: 8,
    },
    mechanism: "Nucleophilic addition to carbon dioxide",
    priority: 1360,
  },
];
