import type { FunctionalGroupPattern } from "../types";

export const aromaticGroups: FunctionalGroupPattern[] = [
  {
    name: "Benzene",
    priority: 31,
    nomenclaturePriority: 22,
    confidence: "High",
    suffix: "benzene",
    prefix: "phenyl",
    smarts: "a1aaaaa1",
    mcatNote:
      "A benzene ring is a six-membered aromatic ring with six delocalized π electrons. It is the most common aromatic system in organic chemistry.",
  },
  {
    name: "Phenol",
    priority: 10.5,
    nomenclaturePriority: 10.5,
    confidence: "High",
    suffix: "-phenol",
    prefix: "hydroxy",
    equivalentNames: ["hydroxybenzene", "phenolic alcohol"],
    smarts: "[a][OX2H]",
    mcatNote:
      "Phenols contain an -OH group directly attached to an aromatic ring. They are more acidic than ordinary alcohols because the phenoxide conjugate base is resonance-stabilized.",
  },
  {
    name: "Aryl ether",
    priority: 19.5,
    nomenclaturePriority: 15.1,
    confidence: "High",
    suffix: "Usually named as substituted benzene",
    prefix: "alkoxy",
    equivalentNames: ["aryl alkyl ether", "anisole derivative"],
    smarts: "[a][OX2][#6]",
    mcatNote:
      "Aryl ethers contain an oxygen directly attached to an aromatic ring. Anisole is the simplest example.",
  },
  {
    name: "Anisole",
    priority: 19.4,
    nomenclaturePriority: 15.05,
    confidence: "High",
    suffix: "Usually named as substituted benzene",
    prefix: "methoxy",
    equivalentNames: ["methoxybenzene"],
    smarts: "c1ccccc1OC",
    mcatNote:
      "Anisole is methoxybenzene, containing a methoxy group directly attached to a benzene ring.",
  },
  {
    name: "Alkylbenzene",
    priority: 31.2,
    nomenclaturePriority: 22.1,
    confidence: "Medium",
    suffix: "Usually named as substituted benzene",
    prefix: "alkyl",
    equivalentNames: [
      "ethylbenzene",
      "propylbenzene",
      "isopropylbenzene",
      "tert-butylbenzene",
    ],
    smarts: "[a][CX4;!R]",
    mcatNote:
      "Alkylbenzenes contain an alkyl substituent attached directly to a benzene ring. Toluene is the simplest member of this family.",
  },
  {
    name: "Toluene",
    priority: 31.1,
    nomenclaturePriority: 22.05,
    confidence: "High",
    suffix: "Usually named as substituted benzene",
    prefix: "methyl",
    equivalentNames: ["methylbenzene"],
    smarts: "[a][CH3;!R]",
    mcatNote:
      "Toluene is methylbenzene, containing a single methyl group directly attached to a benzene ring. It is the simplest alkylbenzene.",
  },
  {
    name: "Aryl amine",
    priority: 14.3,
    nomenclaturePriority: 13.1,
    confidence: "High",
    suffix: "Usually named as substituted aniline",
    prefix: "amino",
    equivalentNames: ["aryl amino compound", "aniline derivative"],
    smarts: "[a][NX3;!$(NC=O);!$(N=C);!$([N+](=O)[O-])]",
    mcatNote:
      "Aryl amines contain a nitrogen directly attached to an aromatic ring. Their lone pair interacts with the aromatic π system, reducing basicity compared with alkyl amines.",
  },
  {
    name: "Aniline",
    priority: 14.2,
    nomenclaturePriority: 13.05,
    confidence: "High",
    suffix: "-aniline",
    prefix: "amino",
    equivalentNames: ["aminobenzene", "phenylamine"],
    smarts: "c1ccccc1N",
    mcatNote:
      "Aniline is aminobenzene, containing an NH₂ group directly attached to a benzene ring. It is the parent aromatic amine.",
  },
  {
    name: "Aryl halide",
    priority: 27.5,
    nomenclaturePriority: 21.1,
    confidence: "High",
    suffix: "Never suffix",
    prefix: "fluoro, chloro, bromo, iodo",
    equivalentNames: ["halobenzene"],
    smarts: "[a][F,Cl,Br,I]",
    mcatNote: "Aryl halides have a halogen directly attached to an aromatic ring.",
  },
  {
    name: "Nitrobenzene",
    priority: 26.5,
    nomenclaturePriority: 20.1,
    confidence: "High",
    suffix: "Never suffix",
    prefix: "nitro",
    equivalentNames: ["nitrobenzene", "aryl nitro compound"],
    smarts: "[a][NX3+](=O)[O-]",
    mcatNote:
      "Nitrobenzenes contain a nitro group attached to an aromatic ring. Nitro groups are strongly electron-withdrawing.",
  },

  {
    name: "Naphthalene",
    priority: 30.8,
    nomenclaturePriority: 21.8,
    confidence: "High",
    suffix: "naphthalene",
    prefix: "naphthyl",
    equivalentNames: ["fused bicyclic arene"],
    smarts: "c1ccc2ccccc2c1",
    mcatNote:
      "Naphthalene is a fused bicyclic aromatic hydrocarbon with two fused benzene rings.",
  },
  {
    name: "Anthracene",
    priority: 30.7,
    nomenclaturePriority: 21.7,
    confidence: "High",
    suffix: "anthracene",
    prefix: "anthracenyl",
    equivalentNames: ["linear tricyclic arene"],
    smarts: "c1ccc2cc3ccccc3cc2c1",
    mcatNote:
      "Anthracene is a linear tricyclic aromatic hydrocarbon with three fused benzene rings.",
  },
  {
    name: "Phenanthrene",
    priority: 30.7,
    nomenclaturePriority: 21.7,
    confidence: "High",
    suffix: "phenanthrene",
    prefix: "phenanthrenyl",
    equivalentNames: ["angular tricyclic arene"],
    smarts: "c1ccc2c(c1)ccc3ccccc23",
    mcatNote:
      "Phenanthrene is an angular tricyclic aromatic hydrocarbon with three fused benzene rings.",
  },
  {
    name: "Indane",
    priority: 30.9,
    nomenclaturePriority: 21.9,
    confidence: "Medium",
    suffix: "indane",
    prefix: "indanyl",
    equivalentNames: ["benzocyclopentane"],
    smarts: "c1ccc2CCCCc2c1",
    mcatNote:
      "Indane contains a benzene ring fused to a saturated five-membered ring. It is not the same as an alkylbenzene.",
  },
  {
    name: "Pyridine",
    priority: 30.6,
    nomenclaturePriority: 21.6,
    confidence: "High",
    suffix: "pyridine",
    prefix: "pyridyl",
    equivalentNames: ["azabenzene"],
    smarts: "n1ccccc1",
    mcatNote:
      "Pyridine is a six-membered aromatic heterocycle with a nitrogen whose lone pair is not part of the aromatic sextet.",
  },
  {
    name: "Pyrrole",
    priority: 30.6,
    nomenclaturePriority: 21.6,
    confidence: "High",
    suffix: "pyrrole",
    prefix: "pyrrolyl",
    smarts: "[nH]1cccc1",
    mcatNote:
      "Pyrrole is a five-membered aromatic heterocycle whose nitrogen lone pair contributes to aromaticity.",
  },
  {
    name: "Furan",
    priority: 30.6,
    nomenclaturePriority: 21.6,
    confidence: "High",
    suffix: "furan",
    prefix: "furyl",
    smarts: "o1cccc1",
    mcatNote:
      "Furan is a five-membered aromatic heterocycle containing oxygen.",
  },
  {
    name: "Thiophene",
    priority: 30.6,
    nomenclaturePriority: 21.6,
    confidence: "High",
    suffix: "thiophene",
    prefix: "thienyl",
    smarts: "s1cccc1",
    mcatNote:
      "Thiophene is a five-membered aromatic heterocycle containing sulfur.",
  },
  {
    name: "Indole",
    priority: 30.5,
    nomenclaturePriority: 21.5,
    confidence: "High",
    suffix: "indole",
    prefix: "indolyl",
    equivalentNames: ["benzopyrrole"],
    smarts: "c1ccc2[nH]ccc2c1",
    mcatNote:
      "Indole is a fused aromatic heterocycle made from benzene fused to pyrrole. It appears in tryptophan and many bioactive molecules.",
  },
];