import type { FunctionalGroupPattern } from "../types";

export const nitrogenGroups: FunctionalGroupPattern[] = [
  {
    name: "Nitrile",
    priority: 7,
    nomenclaturePriority: 7,
    confidence: "High",
    suffix: "-nitrile",
    prefix: "cyano",
    smarts: "[CX2]#N",
    displaySmarts: "[CX2]#N",
    mcatNote:
      "Nitriles contain a carbon-nitrogen triple bond. The nitrile carbon is electrophilic and can be hydrolyzed to carboxylic acid derivatives.",
    category: "functionalGroup",
  },
  {
    name: "Imine",
    priority: 12,
    nomenclaturePriority: 12,
    confidence: "High",
    suffix: "-imine",
    prefix: "imino",
    smarts: "[CX3]=[NX2]",
    displaySmarts: "[CX3]=[NX2]",
    mcatNote:
      "Imines contain a carbon-nitrogen double bond. They are related to carbonyl chemistry and can form from aldehydes or ketones with amines.",
    category: "functionalGroup",
    },
  {
    name: "Hydrazone",
    priority: 13,
    nomenclaturePriority: 12.5,
    confidence: "Medium",
    suffix: "hydrazone",
    prefix: "hydrazono",
    smarts: "[CX3]=[NX2][NX3]",
    displaySmarts: "[CX3]=[NX2][NX3]",
    mcatNote:
      "Hydrazones contain a C=N-N group and are commonly formed from aldehydes or ketones reacting with hydrazine derivatives.",
    category: "functionalGroup",
    },
  {
    name: "Aldoxime",
    priority: 14,
    nomenclaturePriority: 12.6,
    confidence: "High",
    suffix: "aldoxime",
    prefix: "hydroxyimino",
    equivalentNames: ["aldehyde oxime"],
    smarts: "[CX3;H1,H2]=[NX2][OX2H]",
    displaySmarts: "[CX3;H1,H2]=[NX2][OX2H]",
    mcatNote:
      "Aldoximes contain the aldehyde-derived oxime motif R-CH=N-OH. They form when aldehydes react with hydroxylamine.",
    category: "functionalGroup",
  },
  {
    name: "Ketoxime",
    priority: 14.05,
    nomenclaturePriority: 12.61,
    confidence: "High",
    suffix: "ketoxime",
    prefix: "hydroxyimino",
    equivalentNames: ["ketone oxime"],
    smarts: "[CX3H0](=[NX2][OX2H])([#6])[#6]",
    displaySmarts: "[CX3H0]=[NX2][OX2H]",
    mcatNote:
      "Ketoximes contain the ketone-derived oxime motif R2C=N-OH. They form when ketones react with hydroxylamine.",
    category: "functionalGroup",
  },
  {
    name: "Aminoxime",
    priority: 14.1,
    nomenclaturePriority: 12.62,
    confidence: "High",
    suffix: "aminoxime",
    prefix: "amino(hydroxyimino)",
    equivalentNames: ["amidoxime", "amidoxime group"],
    smarts: "[CX3](=[NX2][OX2H])[NX3]",
    displaySmarts: "[CX3](=[NX2][OX2H])[NX3]",
    mcatNote:
      "Aminoximes, often called amidoximes, contain the C(=N-OH)-N motif. They combine an oxime-like C=N-OH unit with an amino substituent on the same carbon.",
    category: "functionalGroup",
  },
  {
    name: "Primary amine",
    priority: 14.8,
    nomenclaturePriority: 14.8,
    confidence: "High",
    suffix: "-amine",
    prefix: "amino",
    equivalentNames: ["1° amine"],
    smarts:
      "[NX3H2;!$([NX3][CX3](=[OX1]));!$(N=C);!$([N+](=O)[O-]);!$(N=N)]",
    displaySmarts: "[NX3H2]",
    mcatNote:
      "Primary amines have nitrogen bonded to one carbon and two hydrogens. They are basic and can act as nucleophiles.",
    category: "functionalGroup",
    },
  {
    name: "Secondary amine",
    priority: 14.9,
    nomenclaturePriority: 14.9,
    confidence: "High",
    suffix: "-amine",
    prefix: "amino",
    equivalentNames: ["2° amine"],
    smarts:
      "[NX3H1;!$([NX3][CX3](=[OX1]));!$(N=C);!$([N+](=O)[O-]);!$(N=N)]",
    displaySmarts: "[NX3H1]",
    mcatNote:
      "Secondary amines have nitrogen bonded to two carbons and one hydrogen. They are generally basic and nucleophilic.",
    category: "functionalGroup",
    },
  {
    name: "Tertiary amine",
    priority: 15.0,
    nomenclaturePriority: 15.0,
    confidence: "High",
    suffix: "-amine",
    prefix: "amino",
    equivalentNames: ["3° amine"],
    smarts:
      "[NX3H0;!$([NX3][CX3](=[OX1]));!$(N=C);!$([N+](=O)[O-]);!$(N=N)]",
    displaySmarts: "[NX3H0]",
    mcatNote:
      "Tertiary amines have nitrogen bonded to three carbons and no N-H bond. They are basic but cannot donate hydrogen bonds.",
    category: "functionalGroup",
    },
    {
  name: "Quaternary ammonium",
  priority: 15.1,
  nomenclaturePriority: 15.1,
  confidence: "High",
  suffix: "ammonium",
  prefix: "ammonio",
  equivalentNames: ["quaternary ammonium ion", "quat"],
  smarts: "[NX4+]",
  displaySmarts: "[NX4+]",
  mcatNote:
    "Quaternary ammonium compounds contain a positively charged nitrogen bonded to four carbon substituents. Unlike amines, they have no lone pair and are permanently positively charged.",
  category: "functionalGroup",
},
  {
    name: "Amine",
    priority: 15.5,
    nomenclaturePriority: 15.5,
    confidence: "Medium",
    suffix: "-amine",
    prefix: "amino",
    smarts:
      "[NX3;!$([NX3][CX3](=[OX1]));!$(N=C);!$([N+](=O)[O-]);!$(N=N)]",
    displaySmarts: "[NX3]",
    mcatNote:
      "Amines are basic and often positively charged at physiological pH. Amino groups are common in amino acids and neurotransmitters.",
    category: "functionalGroup",
    },
  {
    name: "Azo",
    category: "functionalGroup",
    priority: 17,
    nomenclaturePriority: 14,
    confidence: "High",
    suffix: "Never suffix",
    prefix: "azo",
    smarts: "[#6][NX2]=[NX2][#6]",
    mcatNote:
      "Azo compounds contain an N=N linkage between carbon groups. They are often highly conjugated and can appear in dyes.",
    
    },
  {
    name: "Diazo",
    category: "functionalGroup",
    priority: 18,
    nomenclaturePriority: 14.5,
    confidence: "Medium",
    suffix: "Never suffix",
    prefix: "diazo",
    smarts: "[#6][N+]#N",
    mcatNote:
      "Diazo compounds contain a carbon attached to a diazo group. They are reactive nitrogen-containing functional groups.",
  },
  {
    name: "Nitrate ester",
    priority: 25.9,
    nomenclaturePriority: 19.9,
    confidence: "High",
    suffix: "functional class",
    prefix: "nitrooxy",
    equivalentNames: ["alkyl nitrate", "organic nitrate"],
    smarts: "[#6][OX2][N+](=O)[O-]",
    displaySmarts: "[#6]-O-[N+](=O)[O-]",
    mcatNote:
      "Nitrate esters contain the R-O-NO2 group. They are esters of nitric acid and are distinct from nitro compounds, where carbon is bonded directly to nitrogen.",
    category: "functionalGroup",
  },
  {
    name: "Nitro",
    category: "functionalGroup",
    priority: 26,
    nomenclaturePriority: 20,
    confidence: "High",
    suffix: "Never suffix",
    prefix: "nitro",
    smarts: "[NX3+](=O)[O-]",
    displaySmarts: "[NX3+](=O)[O-]",
    mcatNote:
      "Nitro groups contain nitrogen bonded to oxygens and are strongly electron-withdrawing.",
  },
  {
    name: "Isocyanide",
    category: "functionalGroup",
    priority: 29,
    nomenclaturePriority: 13.2,
    confidence: "Medium",
    suffix: "Rare",
    prefix: "isocyano",
    smarts: "[#6][N+]#[C-]",
    displaySmarts: "[N+]#[C-]",
    mcatNote:
      "Isocyanides contain the R-NC connectivity. They are structural isomers of nitriles but have different connectivity.",
  },
  {
    name: "Azide",
    priority: 29.5,
    nomenclaturePriority: 20.5,
    confidence: "High",
    suffix: "Never suffix",
    prefix: "azido",
    equivalentNames: ["organic azide"],
    smarts: "[!#1][N;D2]=[N+;D2]=[N-;D1]",
    displaySmarts: "[N;D2]=[N+;D2]=[N-;D1]",
    mcatNote:
      "Azides contain an N3 group. Organic azides are useful in click chemistry and can be reduced to amines.",
  },
  {
  name: "Azide",
  priority: 29.51,
  nomenclaturePriority: 20.51,
  confidence: "High",
  suffix: "Never suffix",
  prefix: "azido",
  equivalentNames: ["organic azide", "azido group"],
  smarts: "[!#1][N-;D2][N+;D2]#[N;D1]",
  displaySmarts: "[N-;D2][N+;D2]#[N;D1]",
  mcatNote:
    "This is the alternate resonance representation of an organic azide.",
  category: "functionalGroup",
  },
  {
    name: "Isocyanate",
    priority: 30,
    nomenclaturePriority: 18.5,
    confidence: "High",
    suffix: "Rare",
    prefix: "isocyanato",
    smarts: "[NX2]=[CX2]=[OX1]",
    displaySmarts: "[NX2]=[CX2]=[OX1]",
    mcatNote:
      "Isocyanates contain the N=C=O group. They are electrophilic and can react with nucleophiles such as alcohols or amines.",
  },
  {
  name: "Aziridine",
  priority: 15.7,
  nomenclaturePriority: 15.7,
  confidence: "High",
  suffix: "aziridine",
  prefix: "aziridinyl",
  smarts: "[NX3r3]1[#6r3][#6r3]1",
  displaySmarts: "[NX3r3]1[#6r3][#6r3]1",
  mcatNote:
    "Aziridines are three-membered nitrogen heterocycles. Ring strain makes them reactive toward nucleophilic ring opening.",
  category: "functionalGroup",
},
{
  name: "N-oxide",
  priority: 15.8,
  nomenclaturePriority: 15.8,
  confidence: "High",
  suffix: "N-oxide",
  prefix: "oxido",
  smarts: "[NX4+][O-]",
  displaySmarts: "[NX4+][O-]",
  mcatNote:
    "N-oxides contain an N→O bond representation with formal N+ and O−. They commonly form from tertiary amines or heteroaromatic nitrogens.",
  category: "functionalGroup",
},
{
  name: "Nitrone",
  priority: 15.85,
  nomenclaturePriority: 15.85,
  confidence: "High",
  suffix: "nitrone",
  prefix: "nitrone",
  smarts: "[NX3+]([O-])=[#6]",
  displaySmarts: "[NX3+]([O-])=[#6]",
  mcatNote:
    "Nitrones are imine N-oxides with the general structure R2C=N+(O−)R. They are distinct from simple amine N-oxides and are useful 1,3-dipoles in cycloaddition chemistry.",
  category: "functionalGroup",
},
{
  name: "Amidine",
  priority: 16.1,
  nomenclaturePriority: 16.1,
  confidence: "High",
  suffix: "amidine",
  prefix: "amidino",
  smarts: "[#6X3](=[#7X1,#7X2,#7X3])[#7X1,#7X2,#7X3]",
  displaySmarts: "[#6X3](=[#7X1,#7X2,#7X3])[#7X1,#7X2,#7X3]",
  mcatNote:
    "Amidines contain C(=N)-N and are strongly basic because the conjugate acid is resonance-stabilized.",
  category: "functionalGroup",
},
{
  name: "Guanidine",
  priority: 16.2,
  nomenclaturePriority: 16.2,
  confidence: "High",
  suffix: "guanidine",
  prefix: "guanidino",
  smarts: "[#7X1,#7X2,#7X3][#6X3](=[#7X1,#7X2,#7X3])[#7X1,#7X2,#7X3]",
  displaySmarts: "[#7X1,#7X2,#7X3][#6X3](=[#7X1,#7X2,#7X3])[#7X1,#7X2,#7X3]",
  mcatNote:
    "Guanidines are very basic nitrogen functional groups. Arginine contains a guanidinium group.",
  category: "functionalGroup",
},
{
  name: "Nitroso",
  priority: 25.5,
  nomenclaturePriority: 19.5,
  confidence: "High",
  suffix: "Never suffix",
  prefix: "nitroso",
  smarts: "[#6][N]=O",
  displaySmarts: "[N]=O",
  mcatNote:
    "Nitroso compounds contain an N=O group bonded to carbon (R–N=O). They are distinct from nitro compounds and are important intermediates in oxidation, reduction, and diazotization chemistry.",
  category: "functionalGroup",
},

{
  name: "Cyanohydrin",
  priority: 17.6,
  nomenclaturePriority: 17.6,
  confidence: "High",
  suffix: "cyanohydrin",
  prefix: "cyanohydroxy",
  equivalentNames: ["alpha-hydroxynitrile", "α-hydroxynitrile"],
  smarts: "[CX4]([OX2H])[CX2]#[NX1]",
  displaySmarts: "[CX4]([OX2H])[CX2]#[NX1]",
  mcatNote:
    "Cyanohydrins contain an alcohol and nitrile on the same carbon: C(OH)-C≡N. They are commonly formed by adding cyanide to aldehydes or ketones.",
  category: "functionalGroup",
},
{
  name: "Ketone cyanohydrin",
  priority: 17.65,
  nomenclaturePriority: 17.65,
  confidence: "High",
  suffix: "cyanohydrin",
  prefix: "cyanohydroxy",
  equivalentNames: [
    "ketone-derived cyanohydrin",
    "tertiary cyanohydrin",
    "substituted cyanohydrin",
  ],
  smarts: "[CX4H0]([#6])([#6])([OX2H])[CX2]#[NX1]",
  displaySmarts: "[CX4H0]([OX2H])[CX2]#[NX1]",
  mcatNote:
    "Ketone cyanohydrins are cyanohydrins where the OH-bearing carbon has two carbon substituents instead of a hydrogen: R2C(OH)-C≡N.",
  category: "functionalGroup",
},

];