import type { FunctionalGroupPattern } from "../types";

export const siliconGroups: FunctionalGroupPattern[] = [
  {
    name: "Organosilicon",
    priority: 36,
    nomenclaturePriority: 26,
    confidence: "Medium",
    suffix: "Never suffix",
    prefix: "silyl",
    equivalentNames: ["carbon-silicon compound", "organosilane"],
    smarts: "[#6][#14]",
    displaySmarts: "[#6][#14]",
    mcatNote:
      "Organosilicon compounds contain a direct carbon-silicon bond. More specific silicon groups such as silanes, silyl ethers, silanols, and silyl halides should override this broad category.",
    category: "functionalGroup",
  },
  {
    name: "Silane",
    priority: 36.1,
    nomenclaturePriority: 26.1,
    confidence: "High",
    suffix: "silane",
    prefix: "silyl",
    equivalentNames: ["silicon hydride", "hydrosilane"],
    smarts: "[#14H1,#14H2,#14H3,#14H4]",
    displaySmarts: "[#14H1,#14H2,#14H3,#14H4]",
    mcatNote:
      "Silanes contain at least one Si-H bond. Organic hydrosilanes such as Et3SiH are common reducing agents and protecting-group reagents.",
    category: "functionalGroup",
  },
  {
    name: "Silyl ether",
    priority: 36.2,
    nomenclaturePriority: 26.2,
    confidence: "High",
    suffix: "Never suffix",
    prefix: "silyloxy",
    equivalentNames: ["silyl-protected alcohol", "silicon ether"],
    smarts: "[#6][OX2][#14]",
    displaySmarts: "[OX2][#14]",
    mcatNote:
      "Silyl ethers contain a C-O-Si linkage. They are commonly used as protected alcohols, such as TMS, TBS, TBDPS, and TES ethers.",
    category: "functionalGroup",
  },
  {
    name: "Silyl enol ether",
    priority: 36.25,
    nomenclaturePriority: 26.25,
    confidence: "High",
    suffix: "Never suffix",
    prefix: "silyloxyalkenyl",
    equivalentNames: ["siloxy alkene"],
    smarts: "[CX3]=[CX3][OX2][#14]",
    displaySmarts: "[CX3]=[CX3][OX2][#14]",
    mcatNote:
      "Silyl enol ethers contain an alkene attached to an O-Si group. They are important enolate equivalents in carbon-carbon bond-forming reactions.",
    category: "functionalGroup",
  },
  {
    name: "Silanol",
    priority: 36.3,
    nomenclaturePriority: 26.3,
    confidence: "High",
    suffix: "silanol",
    prefix: "hydroxysilyl",
    equivalentNames: ["silicon alcohol"],
    smarts: "[#14][OX2H]",
    displaySmarts: "[#14][OX2H]",
    mcatNote:
      "Silanols contain an Si-OH group. They are silicon analogs of alcohols and can condense to form siloxanes.",
    category: "functionalGroup",
  },
  {
    name: "Siloxane",
    priority: 36.4,
    nomenclaturePriority: 26.4,
    confidence: "High",
    suffix: "siloxane",
    prefix: "siloxy",
    equivalentNames: ["Si-O-Si linkage"],
    smarts: "[#14][OX2][#14]",
    displaySmarts: "[#14][OX2][#14]",
    mcatNote:
      "Siloxanes contain an Si-O-Si linkage. They are the backbone motif of silicone materials.",
    category: "functionalGroup",
  },
  {
    name: "Silyl halide",
    priority: 36.5,
    nomenclaturePriority: 26.5,
    confidence: "High",
    suffix: "Never suffix",
    prefix: "halosilyl",
    equivalentNames: ["chlorosilane", "bromosilane", "fluorosilane", "iodosilane"],
    smarts: "[#14][F,Cl,Br,I]",
    displaySmarts: "[#14][F,Cl,Br,I]",
    mcatNote:
      "Silyl halides contain a silicon-halogen bond. Chlorosilanes such as TMSCl and TBSCl are common reagents for forming silyl ethers.",
    category: "functionalGroup",
  },
  {
    name: "Disilane",
    priority: 36.6,
    nomenclaturePriority: 26.6,
    confidence: "Medium",
    suffix: "disilane",
    prefix: "disilanyl",
    equivalentNames: ["Si-Si bond"],
    smarts: "[#14][#14]",
    displaySmarts: "[#14][#14]",
    mcatNote:
      "Disilanes contain a direct silicon-silicon bond.",
    category: "functionalGroup",
  },
];