import type { FunctionalGroupPattern } from "../types";

export const sulfurGroups: FunctionalGroupPattern[] = [
  {
    name: "Sulfonic acid",
    priority: 2,
    nomenclaturePriority: 2,
    confidence: "High",
    suffix: "-sulfonic acid",
    prefix: "sulfo",
    smarts: "S(=O)(=O)[OX2H]",
    displaySmarts: "S(=O)(=O)[OX2H]",
    mcatNote:
      "Sulfonic acids are very strong organic acids because the conjugate base is highly resonance-stabilized over multiple oxygens.",
    category: "functionalGroup",
  },
  {
    name: "Sulfonamide",
    priority: 2.5,
    nomenclaturePriority: 2.5,
    confidence: "High",
    suffix: "sulfonamide",
    prefix: "sulfonamido",
    smarts: "S(=O)(=O)N",
    displaySmarts: "S(=O)(=O)N",
    mcatNote:
      "Sulfonamides contain a sulfonyl group bonded to nitrogen. They are common in medicinal chemistry and sulfa drugs.",
    category: "functionalGroup",
    },
  
    
  {
    name: "Thiol",
    priority: 11,
    nomenclaturePriority: 11,
    confidence: "High",
    suffix: "-thiol",
    prefix: "sulfanyl",
    smarts: "[#6][SX2H]",
    displaySmarts: "[SX2H]",
    mcatNote:
      "Thiols contain an -SH group. They are sulfur analogs of alcohols and can form disulfide bonds, especially in cysteine residues.",
    category: "functionalGroup",
    },
  {
    name: "Disulfide",
    priority: 11.5,
    nomenclaturePriority: 11.5,
    confidence: "High",
    suffix: "disulfide",
    prefix: "disulfanyl",
    smarts: "[SX2][SX2]",
    displaySmarts: "[SX2][SX2]",
    mcatNote:
      "Disulfides contain an S-S bond and commonly link cysteine residues in proteins.",
    category: "functionalGroup",
    },

  {
    name: "Thioether",
    priority: 20,
    nomenclaturePriority: 16,
    confidence: "High",
    suffix: "Never suffix",
    prefix: "alkylthio",
    smarts: "[#6][SX2][#6]",
    displaySmarts: "[SX2]",
    mcatNote:
      "Thioethers, also called sulfides, contain sulfur between two carbon groups. Methionine contains a thioether.",
    category: "functionalGroup",
    },
  {
    name: "Sulfoxide",
    priority: 21,
    nomenclaturePriority: 16.5,
    confidence: "High",
    suffix: "Never suffix",
    prefix: "sulfinyl",
    smarts: "[#6][SX3](=O)[#6]",
    displaySmarts: "[SX3](=O)",
    mcatNote:
      "Sulfoxides contain sulfur bonded to oxygen and two carbon groups. The S=O bond is polar.",
    category: "functionalGroup",
    },
    {  
    name: "Sulfonyl chloride",
    priority: 32.6,
    nomenclaturePriority: 23.6,
    confidence: "High",
    suffix: "sulfonyl chloride",
    prefix: "chlorosulfonyl",
    equivalentNames: ["sulfonic acid chloride"],
    smarts: "[#6][SX4](=[OX1])(=[OX1])Cl",
    displaySmarts: "[SX4](=[OX1])(=[OX1])Cl",
    mcatNote:
      "Sulfonyl chlorides contain the R-SO2-Cl group. They are reactive sulfonic acid derivatives commonly used to make sulfonamides and sulfonate esters.",
    category: "functionalGroup",
    },
  {
    name: "Sulfone",
    priority: 22,
    nomenclaturePriority: 16.6,
    confidence: "High",
    suffix: "Never suffix",
    prefix: "sulfonyl",
    smarts: "[#6][SX4](=O)(=O)[#6]",
    displaySmarts: "[SX4](=O)(=O)",
    mcatNote:
      "Sulfones contain sulfur double-bonded to two oxygens and bonded to two carbon groups. They are highly polar sulfur-containing groups.",
    category: "functionalGroup",
    },
  {
    name: "Sulfonate ester",
    priority: 22.2,
    nomenclaturePriority: 16.7,
    confidence: "High",
    suffix: "sulfonate",
    prefix: "sulfonyloxy",
    smarts: "S(=O)(=O)O[#6]",
    displaySmarts: "S(=O)(=O)O",
    mcatNote:
      "Sulfonate esters are excellent leaving groups and include tosylates, mesylates, and triflates.",
    category: "functionalGroup",
    },
  {
    name: "Isothiocyanate",
    priority: 34,
    nomenclaturePriority: 24.5,
    confidence: "High",
    suffix: "isothiocyanate",
    prefix: "isothiocyanato",
    smarts: "N=C=S",
    displaySmarts: "N=C=S",
    mcatNote:
      "Isothiocyanates contain the N=C=S group and are electrophilic compounds found in mustard oils and many natural products.",
    category: "functionalGroup",
    },
      {
    name: "Thioester",
    priority: 5.8,
    nomenclaturePriority: 5.8,
    confidence: "High",
    suffix: "thioate",
    prefix: "thioester",
    smarts: "[CX3](=O)[SX2][#6]",
    displaySmarts: "[CX3](=O)[SX2]",
    mcatNote:
      "Thioesters are sulfur analogs of esters. They are significantly more reactive than ordinary esters and are central to biochemistry (e.g. acetyl-CoA).",
    category: "functionalGroup",
  },
  {
    name: "Thioamide",
    priority: 6.8,
    nomenclaturePriority: 6.8,
    confidence: "High",
    suffix: "thioamide",
    prefix: "carbothioamido",
    smarts: "[CX3](=[SX1])[NX3]",
    displaySmarts: "[CX3](=[SX1])[NX3]",
    mcatNote:
      "Thioamides are sulfur analogs of amides in which sulfur replaces the carbonyl oxygen.",
    category: "functionalGroup",
  },
  {
    name: "Thioketone",
    priority: 8.8,
    nomenclaturePriority: 8.8,
    confidence: "Medium",
    suffix: "thioketone",
    prefix: "thioxo",
    smarts: "[#6][CX3](=[SX1])[#6]",
    displaySmarts: "[CX3]=[SX1]",
    mcatNote:
      "Thioketones contain a carbon-sulfur double bond instead of a carbonyl oxygen. They are much more reactive than ketones.",
    category: "functionalGroup",
  },
  {
    name: "Thioaldehyde",
    priority: 8.9,
    nomenclaturePriority: 8.9,
    confidence: "Medium",
    suffix: "thial",
    prefix: "thioxo",
    smarts: "[CX3H1]=[SX1]",
    displaySmarts: "[CX3H1]=[SX1]",
    mcatNote:
      "Thioaldehydes are sulfur analogs of aldehydes and are highly reactive.",
    category: "functionalGroup",
  },
  {
    name: "Thiocarboxylic acid",
    priority: 3,
    nomenclaturePriority: 3,
    confidence: "Medium",
    suffix: "thiocarboxylic acid",
    prefix: "sulfanylcarbonyl",
    smarts: "[CX3](=[SX1])[OX2H]",
    displaySmarts: "[CX3](=[SX1])[OX2H]",
    mcatNote:
      "Thiocarboxylic acids are sulfur analogs of carboxylic acids in which oxygen is replaced by sulfur.",
    category: "functionalGroup",
  },
  {
    name: "Sulfenic acid",
    priority: 12.2,
    nomenclaturePriority: 12.2,
    confidence: "Medium",
    suffix: "sulfenic acid",
    prefix: "sulfenyl",
    smarts: "[SX2][OX2H]",
    displaySmarts: "[SX2][OX2H]",
    mcatNote:
      "Sulfenic acids are reactive sulfur oxidation intermediates often observed in biological oxidation processes.",
    category: "functionalGroup",
  },
  {
    name: "Sulfinic acid",
    priority: 2.2,
    nomenclaturePriority: 2.2,
    confidence: "Medium",
    suffix: "sulfinic acid",
    prefix: "sulfino",
    smarts: "[SX3](=O)[OX2H]",
    displaySmarts: "[SX3](=O)[OX2H]",
    mcatNote:
      "Sulfinic acids are partially oxidized sulfur acids lying between thiols and sulfonic acids.",
    category: "functionalGroup",
  },
];