import type { AcidBaseSiteRule } from "./types";

export const ACID_SITE_RULES = [
  {
    id: "oxonium-oh",
    kind: "acid",
    priority: 1,
    relatedGroup: "Oxonium ion",
    siteLabel: "oxonium O–H proton",
    smarts: "[O+;H1,H2,H3]",
    siteAtomIndexInMatch: 0,
    pkaCenter: -1.5,
    pkaRange: [-3, 0],
    confidence: "High",
    atom: "The proton is attached to positively charged oxygen.",
    resonance: "Resonance depends on the surrounding structure, but charge neutralization is already strongly favorable.",
    induction: "Positive charge on oxygen strongly polarizes and weakens the O–H bond.",
    orbital: "Deprotonation restores a neutral oxygen lone-pair arrangement.",
    explanation: "Oxonium ions are strong acids because losing H+ removes a positive charge from oxygen.",
  },
  {
    id: "sulfonic-acid-oh",
    kind: "acid",
    priority: 2,
    relatedGroup: "Sulfonic acid",
    siteLabel: "sulfonic acid O–H proton",
    smarts: "[SX4](=[OX1])(=[OX1])[OX2H1]",
    siteAtomIndexInMatch: 3,
    pkaCenter: -0.5,
    pkaRange: [-2, 1],
    confidence: "High",
    atom: "Deprotonation places negative charge on oxygen.",
    resonance: "Sulfonate delocalizes the negative charge over three oxygens.",
    induction: "The two S=O bonds strongly withdraw electron density.",
    orbital: "The sulfonate framework distributes charge over several S–O interactions.",
    explanation: "Extensive charge delocalization and strong electron withdrawal make sulfonic acids very acidic.",
  },
  {
    id: "imide-nh",
    kind: "acid",
    priority: 3,
    relatedGroup: "Imide",
    siteLabel: "imide N–H proton",
    smarts: "[CX3](=[OX1])[NX3H1][CX3](=[OX1])",
    siteAtomIndexInMatch: 2,
    pkaCenter: 8.5,
    pkaRange: [7.5, 10],
    confidence: "Medium",
    atom: "Deprotonation places negative charge primarily on nitrogen.",
    resonance: "The anion is delocalized into two adjacent carbonyl groups.",
    induction: "Two carbonyl groups withdraw electron density and stabilize the conjugate base.",
    orbital: "Nitrogen and both carbonyl groups can share a conjugated p-orbital system.",
    explanation: "Two carbonyl groups stabilize an imide conjugate base, making the N–H proton appreciably acidic.",
  },
  {
    id: "beta-dicarbonyl-alpha-ch",
    kind: "acid",
    priority: 4,
    relatedGroup: "1,3-Dicarbonyl compound",
    siteLabel: "carbon between two carbonyl groups",
    smarts: "[CX3](=[OX1])-[CX4;H1,H2]-[CX3](=[OX1])",
    siteAtomIndexInMatch: 2,
    pkaCenter: 9,
    pkaRange: [8, 11],
    confidence: "Medium",
    atom: "Deprotonation places negative charge on the carbon between two carbonyls.",
    resonance: "The enolate charge can delocalize into either carbonyl group.",
    induction: "Both carbonyls withdraw electron density and stabilize the conjugate base.",
    orbital: "The central carbon can become sp2-hybridized and join an extended conjugated system.",
    explanation: "Delocalization into two carbonyl groups makes 1,3-dicarbonyl alpha hydrogens much more acidic than ordinary carbonyl alpha hydrogens.",
  },
  {
    id: "sulfonamide-nh",
    kind: "acid",
    priority: 5,
    relatedGroup: "Sulfonamide",
    siteLabel: "sulfonamide N–H proton",
    smarts: "[SX4](=[OX1])(=[OX1])[NX3;H1,H2]",
    siteAtomIndexInMatch: 3,
    pkaCenter: 10,
    pkaRange: [7, 12],
    confidence: "Medium",
    atom: "Deprotonation places negative charge on nitrogen.",
    resonance: "The charge is delocalized into the sulfonyl group.",
    induction: "The sulfonyl group strongly withdraws electron density.",
    orbital: "Nitrogen can overlap with the S–O bonding framework to spread charge.",
    explanation: "Sulfonyl stabilization makes sulfonamide N–H protons substantially more acidic than amine N–H protons.",
  },
  {
    id: "hydroperoxide-oh",
    kind: "acid",
    priority: 6,
    relatedGroup: "Hydroperoxide",
    siteLabel: "hydroperoxide O–H proton",
    smarts: "[OX2H1]-[OX2]",
    siteAtomIndexInMatch: 0,
    pkaCenter: 11.5,
    pkaRange: [10.5, 12.5],
    confidence: "Medium",
    atom: "Deprotonation places negative charge on terminal oxygen.",
    resonance: "Peroxide anions have limited conventional resonance stabilization.",
    induction: "The adjacent oxygen withdraws electron density and stabilizes the conjugate base.",
    orbital: "The O–O bond and polarizable oxygen lone pairs help distribute electron density.",
    explanation: "An adjacent oxygen makes hydroperoxides more acidic than ordinary alcohols.",
  },
  {
    id: "phenol-oh",
    kind: "acid",
    priority: 6,
    relatedGroup: "Phenol",
    siteLabel: "phenolic O–H proton",
    smarts: "[c][OX2H1]",
    siteAtomIndexInMatch: 1,
    pkaCenter: 10,
    pkaRange: [9, 11],
    confidence: "High",
    atom: "Deprotonation places negative charge on oxygen.",
    resonance: "Phenoxide delocalizes part of the charge into the aromatic ring.",
    induction: "Electron-withdrawing ring substituents generally increase acidity.",
    orbital: "An oxygen p orbital overlaps with the aromatic π system.",
    explanation: "Resonance stabilization of phenoxide makes phenols more acidic than ordinary alcohols.",
  },
  {
    id: "thiol-sh",
    kind: "acid",
    priority: 7,
    relatedGroup: "Thiol",
    siteLabel: "thiol S–H proton",
    smarts: "[SX2H1;!$([S][SX4](=O)(=O))]",
    siteAtomIndexInMatch: 0,
    pkaCenter: 10.5,
    pkaRange: [9, 12],
    confidence: "High",
    atom: "Deprotonation places negative charge on sulfur.",
    resonance: "Simple thiolates usually have little resonance stabilization.",
    induction: "Electron-withdrawing substituents stabilize thiolate and increase acidity.",
    orbital: "Sulfur's large, polarizable valence orbitals spread negative charge better than oxygen does.",
    explanation: "The large sulfur atom stabilizes negative charge, so thiols are more acidic than comparable alcohols.",
  },
  {
    id: "pyridinium-nh",
    kind: "acid",
    priority: 8,
    relatedGroup: "Pyridinium-like ion",
    siteLabel: "protonated aromatic nitrogen",
    smarts: "[nH+]",
    siteAtomIndexInMatch: 0,
    pkaCenter: 5.2,
    pkaRange: [3, 7],
    confidence: "Medium",
    atom: "The proton is attached to positively charged aromatic nitrogen.",
    resonance: "Deprotonation restores the neutral aromatic heterocycle.",
    induction: "Ring substituents can strongly change this value.",
    orbital: "Deprotonation restores the pyridine-like lone pair without disrupting aromaticity.",
    explanation: "Pyridinium-like ions are more acidic than alkylammonium ions because the corresponding aromatic base is less basic.",
  },
  {
    id: "ammonium-nh",
    kind: "acid",
    priority: 9,
    relatedGroup: "Ammonium ion",
    siteLabel: "ammonium N–H proton",
    smarts: "[N+;H1,H2,H3,H4;!$([N+](=O)[O-])]",
    siteAtomIndexInMatch: 0,
    pkaCenter: 10.5,
    pkaRange: [9, 12],
    confidence: "Medium",
    atom: "The proton is attached to positively charged nitrogen.",
    resonance: "Resonance depends on the neutral amine formed after deprotonation.",
    induction: "Electron-withdrawing groups lower the pKa of ammonium ions.",
    orbital: "Deprotonation restores a neutral nitrogen lone pair.",
    explanation: "Ammonium ions donate H+ to regenerate neutral amines; their acidity tracks the basicity of that amine.",
  },
  {
    id: "carboxylic-acid-oh",
    kind: "acid",
    priority: 10,
    relatedGroup: "Carboxylic acid",
    siteLabel: "carboxylic acid O–H proton",
    smarts: "[CX3](=[OX1])[OX2H1]",
    siteAtomIndexInMatch: 2,
    pkaCenter: 4.8,
    pkaRange: [3.5, 5.5],
    confidence: "High",
    atom: "Deprotonation places negative charge on oxygen.",
    resonance: "Carboxylate shares the negative charge between two oxygens.",
    induction: "Electron-withdrawing substituents stabilize carboxylate and lower pKa.",
    orbital: "Parallel p orbitals delocalize charge across the O–C–O unit.",
    explanation: "Two equivalent resonance contributors strongly stabilize the carboxylate conjugate base.",
  },
  {
    id: "nitro-alpha-ch",
    kind: "acid",
    priority: 11,
    relatedGroup: "Nitroalkane",
    siteLabel: "carbon alpha to a nitro group",
    smarts: "[CX4;H1,H2,H3]-[NX3+](=[OX1])[O-]",
    siteAtomIndexInMatch: 0,
    pkaCenter: 17,
    pkaRange: [15, 19],
    confidence: "Medium",
    atom: "Deprotonation places negative charge on the carbon beside the nitro group.",
    resonance: "The nitronate conjugate base delocalizes charge onto oxygen.",
    induction: "The nitro group strongly withdraws electron density.",
    orbital: "The alpha carbon becomes conjugated with the nitro group.",
    explanation: "Nitronate resonance makes alpha hydrogens of nitroalkanes significantly acidic.",
  },
  {
    id: "pyrrole-nh",
    kind: "acid",
    priority: 12,
    relatedGroup: "Pyrrole-like aromatic N–H",
    siteLabel: "pyrrolic N–H proton",
    smarts: "[nH;+0]",
    siteAtomIndexInMatch: 0,
    pkaCenter: 17.5,
    pkaRange: [15, 19],
    confidence: "Medium",
    atom: "Deprotonation places negative charge on aromatic nitrogen.",
    resonance: "The conjugate base delocalizes charge through the aromatic heterocycle.",
    induction: "Electron-withdrawing ring substituents can increase N–H acidity.",
    orbital: "The nitrogen lone pair and ring π system reorganize after deprotonation.",
    explanation: "Pyrrole-like N–H protons are more acidic than amine N–H protons because the conjugate base is resonance-stabilized.",
  },
  {
    id: "amide-nh",
    kind: "acid",
    priority: 12,
    relatedGroup: "Amide",
    siteLabel: "amide N–H proton",
    smarts: "[CX3](=[OX1])[NX3;H1,H2]",
    siteAtomIndexInMatch: 2,
    pkaCenter: 16,
    pkaRange: [14, 18],
    confidence: "Medium",
    atom: "Deprotonation places negative charge mainly on nitrogen.",
    resonance: "The anion can delocalize into the adjacent carbonyl.",
    induction: "The carbonyl withdraws electron density and stabilizes the conjugate base.",
    orbital: "Nitrogen and the carbonyl can share a conjugated p-orbital system.",
    explanation: "Carbonyl stabilization makes amide N–H protons more acidic than amine N–H protons.",
  },
  {
    id: "water-oh",
    kind: "acid",
    priority: 13,
    relatedGroup: "Water",
    siteLabel: "water O–H proton",
    smarts: "[OH2;+0]",
    siteAtomIndexInMatch: 0,
    pkaCenter: 15.7,
    pkaRange: [15.5, 16],
    confidence: "High",
    atom: "Deprotonation places negative charge on oxygen.",
    resonance: "Hydroxide has no resonance stabilization.",
    induction: "No carbon substituent modifies the oxygen significantly.",
    orbital: "The negative charge remains localized in oxygen lone-pair orbitals.",
    explanation: "Water is a weak acid, but it is slightly more acidic than many simple alcohols.",
  },
  {
    id: "alcohol-oh",
    kind: "acid",
    priority: 14,
    relatedGroup: "Alcohol",
    siteLabel: "alcohol O–H proton",
    smarts: "[OX2H1;+0;!$([O][O]);!$([O][CX3](=O));!$([O][SX4](=O)(=O));!$([O][PX4](=O));!$([O][c])]",
    siteAtomIndexInMatch: 0,
    pkaCenter: 16.5,
    pkaRange: [15, 19],
    confidence: "Medium",
    atom: "Deprotonation places negative charge on oxygen.",
    resonance: "Simple alkoxides generally lack resonance stabilization.",
    induction: "Nearby electron-withdrawing groups can stabilize alkoxide and increase acidity.",
    orbital: "The negative charge remains mostly localized in oxygen lone-pair orbitals.",
    explanation: "Alcohols are weak acids because their alkoxide conjugate bases have localized negative charge.",
  },
  {
    id: "ketone-aldehyde-alpha-ch",
    kind: "acid",
    priority: 15,
    relatedGroup: "Aldehyde or ketone",
    siteLabel: "carbon alpha to an aldehyde or ketone",
    smarts: "[CX3;!$([CX3]-[OX2,NX3,SX2])](=[OX1])-[CX4;H1,H2,H3]",
    siteAtomIndexInMatch: 2,
    pkaCenter: 20,
    pkaRange: [18, 22],
    confidence: "Medium",
    atom: "Deprotonation places negative charge on the alpha carbon.",
    resonance: "The enolate conjugate base delocalizes charge between carbon and oxygen.",
    induction: "The carbonyl withdraws electron density and stabilizes the adjacent anion.",
    orbital: "The alpha carbon becomes sp2-hybridized and conjugated with the carbonyl.",
    explanation: "Enolate resonance makes alpha hydrogens of aldehydes and ketones moderately acidic.",
  },
  {
    id: "ester-alpha-ch",
    kind: "acid",
    priority: 16,
    relatedGroup: "Ester",
    siteLabel: "carbon alpha to an ester",
    smarts: "[OX2H0;+0][CX3](=[OX1])-[CX4;H1,H2,H3]",
    siteAtomIndexInMatch: 3,
    pkaCenter: 25,
    pkaRange: [23, 27],
    confidence: "Medium",
    atom: "Deprotonation places negative charge on the alpha carbon.",
    resonance: "The enolate charge delocalizes into the ester carbonyl.",
    induction: "The ester carbonyl withdraws electron density, though the alkoxy group reduces this effect relative to ketones.",
    orbital: "The alpha carbon becomes conjugated with the carbonyl.",
    explanation: "Ester alpha hydrogens are acidic enough for enolate formation but less acidic than ketone alpha hydrogens.",
  },
  {
    id: "nitrile-alpha-ch",
    kind: "acid",
    priority: 17,
    relatedGroup: "Nitrile",
    siteLabel: "carbon alpha to a nitrile",
    smarts: "[CX4;H1,H2,H3]-[CX2]#[NX1]",
    siteAtomIndexInMatch: 0,
    pkaCenter: 25,
    pkaRange: [23, 27],
    confidence: "Medium",
    atom: "Deprotonation places negative charge on carbon beside the nitrile.",
    resonance: "The anion can delocalize toward the nitrile nitrogen.",
    induction: "The strongly electron-withdrawing nitrile stabilizes the adjacent carbanion.",
    orbital: "The alpha carbon can align with the nitrile π system.",
    explanation: "Nitrile stabilization makes alpha hydrogens considerably more acidic than ordinary alkane hydrogens.",
  },
  {
    id: "terminal-alkyne-ch",
    kind: "acid",
    priority: 18,
    relatedGroup: "Terminal alkyne",
    siteLabel: "terminal alkyne C–H proton",
    smarts: "[CX2H1]#[CX2]",
    siteAtomIndexInMatch: 0,
    pkaCenter: 25,
    pkaRange: [24, 26],
    confidence: "High",
    atom: "Deprotonation places negative charge on carbon.",
    resonance: "Simple acetylide ions usually lack additional resonance stabilization.",
    induction: "Electron-withdrawing substituents can further stabilize the acetylide.",
    orbital: "An sp orbital has 50% s-character and holds negative charge close to the nucleus.",
    explanation: "High s-character makes terminal alkynes more acidic than alkenes and alkanes.",
  },
  {
    id: "amide-alpha-ch",
    kind: "acid",
    priority: 19,
    relatedGroup: "Amide",
    siteLabel: "carbon alpha to an amide carbonyl",
    smarts: "[NX3][CX3](=[OX1])-[CX4;H1,H2,H3]",
    siteAtomIndexInMatch: 3,
    pkaCenter: 30,
    pkaRange: [28, 32],
    confidence: "Low",
    atom: "Deprotonation places negative charge on the alpha carbon.",
    resonance: "The resulting enolate can delocalize into the amide carbonyl.",
    induction: "Amide resonance donation reduces the carbonyl's electron-withdrawing effect.",
    orbital: "The alpha carbon can become conjugated with the carbonyl.",
    explanation: "Amide alpha hydrogens are less acidic than ketone or ester alpha hydrogens because the amide carbonyl is less electron-withdrawing.",
  },
  {
    id: "aniline-nh",
    kind: "acid",
    priority: 20,
    relatedGroup: "Aniline",
    siteLabel: "aniline N–H proton",
    smarts: "[c]-[NX3;H1,H2;+0;!$([N][CX3](=O))]",
    siteAtomIndexInMatch: 1,
    pkaCenter: 30,
    pkaRange: [28, 35],
    confidence: "Low",
    atom: "Deprotonation places negative charge on nitrogen.",
    resonance: "The anilide conjugate base can delocalize charge into the aromatic ring.",
    induction: "Electron-withdrawing ring substituents increase N–H acidity.",
    orbital: "A nitrogen p orbital can overlap with the aromatic π system.",
    explanation: "Aromatic delocalization makes aniline N–H protons somewhat more acidic than ordinary amine N–H protons.",
  },
  {
    id: "amine-nh",
    kind: "acid",
    priority: 21,
    relatedGroup: "Amine",
    siteLabel: "amine N–H proton",
    smarts: "[NX3;H1,H2;+0;!$([N][CX3](=O));!$([N][SX4](=O)(=O));!$([N][c]);!$([N][CX3](=[NX2]));!$(N=C);!$(N=N)]",
    siteAtomIndexInMatch: 0,
    pkaCenter: 38,
    pkaRange: [35, 40],
    confidence: "Low",
    atom: "Deprotonation places negative charge on nitrogen.",
    resonance: "Simple amide ions derived from amines lack major resonance stabilization.",
    induction: "Electron-withdrawing substituents can increase N–H acidity.",
    orbital: "The negative charge remains largely localized on nitrogen.",
    explanation: "Neutral amines are very weak acids because their nitrogen-centered conjugate bases are poorly stabilized.",
  },
  {
    id: "ammonia-nh",
    kind: "acid",
    priority: 22,
    relatedGroup: "Ammonia",
    siteLabel: "ammonia N–H proton",
    smarts: "[NH3;+0]",
    siteAtomIndexInMatch: 0,
    pkaCenter: 38,
    pkaRange: [36, 40],
    confidence: "Medium",
    atom: "Deprotonation places negative charge on nitrogen.",
    resonance: "The amide ion has no resonance stabilization.",
    induction: "No carbon substituents stabilize the negative charge.",
    orbital: "The negative charge remains localized in a nitrogen lone-pair orbital.",
    explanation: "Ammonia is an extremely weak acid because its conjugate base, amide ion, is a very strong base.",
  },
  {
    id: "aromatic-ch",
    kind: "acid",
    priority: 90,
    relatedGroup: "Arene",
    siteLabel: "aromatic C–H proton",
    smarts: "[cH]",
    siteAtomIndexInMatch: 0,
    pkaCenter: 43,
    pkaRange: [40, 45],
    confidence: "Low",
    fallbackOnly: true,
    atom: "Deprotonation places negative charge on an aromatic carbon.",
    resonance: "The aryl anion is not stabilized like a benzyl anion and may disrupt favorable orbital occupancy.",
    induction: "Strong electron-withdrawing substituents can increase arene C–H acidity.",
    orbital: "The lone pair occupies an in-plane sp2-type orbital rather than the aromatic π system.",
    explanation: "Ordinary aromatic C–H bonds are extremely weakly acidic.",
  },
  {
    id: "alkene-ch",
    kind: "acid",
    priority: 91,
    relatedGroup: "Alkene",
    siteLabel: "vinylic C–H proton",
    smarts: "[CX3;H1,H2]=[CX3]",
    siteAtomIndexInMatch: 0,
    pkaCenter: 44,
    pkaRange: [42, 46],
    confidence: "Low",
    fallbackOnly: true,
    atom: "Deprotonation places negative charge on an sp2 carbon.",
    resonance: "A simple vinyl anion lacks the stabilization of an allylic anion.",
    induction: "Substituent effects are usually modest unless strong withdrawing groups are present.",
    orbital: "An sp2 orbital stabilizes charge slightly better than an sp3 orbital.",
    explanation: "Vinylic C–H bonds are extremely weak acids, though slightly more acidic than typical alkane C–H bonds.",
  },
  {
    id: "alkane-ch",
    kind: "acid",
    priority: 99,
    relatedGroup: "Alkane",
    siteLabel: "alkane C–H proton",
    smarts: "[CX4;H1,H2,H3,H4;+0]",
    siteAtomIndexInMatch: 0,
    pkaCenter: 50,
    pkaRange: [48, 52],
    confidence: "Low",
    fallbackOnly: true,
    atom: "Deprotonation places negative charge on an sp3 carbon.",
    resonance: "A simple alkyl carbanion lacks resonance stabilization.",
    induction: "Alkyl substitution generally does not stabilize negative charge.",
    orbital: "An sp3 orbital holds negative charge relatively far from the nucleus.",
    explanation: "Alkanes are among the weakest common Brønsted acids because alkyl carbanions are highly unstable.",
  },
] satisfies readonly AcidBaseSiteRule[];