import type { AcidBaseSiteRule } from "./types";

export const BASE_SITE_RULES = [
  {
    id: "alkyl-carbanion",
    kind: "base",
    priority: 1,
    relatedGroup: "Carbanion",
    siteLabel: "negatively charged carbon",
    smarts: "[C-;!$([C-]#[C]);!$([C-]-[CX3](=O));!$([C-]-[CX2]#[N]);!$([C-]-[c]);!$([C-]-[CX3]=[CX3])]",
    siteAtomIndexInMatch: 0,
    pkaCenter: 50,
    pkaRange: [40, 52],
    confidence: "Low",
    atom: "The basic site is a negatively charged carbon.",
    resonance: "This generic rule assumes no strong resonance stabilization.",
    induction: "Electron-withdrawing groups can greatly reduce carbanion basicity.",
    orbital: "Localized carbon lone pairs are high in energy and strongly proton-seeking.",
    explanation: "A localized carbanion is an extremely strong base because protonation forms a very weakly acidic C–H bond.",
  },
  {
    id: "benzylic-carbanion",
    kind: "base",
    priority: 2,
    relatedGroup: "Benzylic carbanion",
    siteLabel: "benzylic carbon anion",
    smarts: "[C-]-[c]",
    siteAtomIndexInMatch: 0,
    pkaCenter: 41,
    pkaRange: [38, 43],
    confidence: "Low",
    atom: "The basic site is a negatively charged carbon adjacent to an aromatic ring.",
    resonance: "The charge can delocalize into the aromatic ring.",
    induction: "Ring substituents can substantially change benzylic carbanion stability.",
    orbital: "The carbanion p orbital overlaps with the ring π system.",
    explanation: "Benzylic resonance makes this carbanion less basic than a localized alkyl carbanion.",
  },
  {
    id: "allylic-carbanion",
    kind: "base",
    priority: 3,
    relatedGroup: "Allylic carbanion",
    siteLabel: "allylic carbon anion",
    smarts: "[C-]-[CX3]=[CX3]",
    siteAtomIndexInMatch: 0,
    pkaCenter: 43,
    pkaRange: [40, 45],
    confidence: "Low",
    atom: "The basic site is a negatively charged carbon adjacent to a C=C bond.",
    resonance: "The charge delocalizes across the allylic π system.",
    induction: "Substituents on the alkene can alter anion stability.",
    orbital: "The carbanion p orbital overlaps with the neighboring π bond.",
    explanation: "Allylic resonance lowers basicity relative to a localized alkyl carbanion.",
  },
  {
    id: "amide-anion",
    kind: "base",
    priority: 2,
    relatedGroup: "Amide anion",
    siteLabel: "negatively charged nitrogen",
    smarts: "[N-;!$([N-][CX3](=O))]",
    siteAtomIndexInMatch: 0,
    pkaCenter: 38,
    pkaRange: [35, 40],
    confidence: "Medium",
    atom: "The basic site is a negatively charged nitrogen.",
    resonance: "This generic rule assumes the charge is not strongly resonance-delocalized.",
    induction: "Electron-withdrawing substituents reduce nitrogen basicity.",
    orbital: "The nitrogen lone pair is high in energy and readily accepts a proton.",
    explanation: "Negatively charged nitrogen is a very strong base because protonation gives a neutral amine.",
  },
  {
    id: "enolate-carbanion",
    kind: "base",
    priority: 3,
    relatedGroup: "Enolate-like carbanion",
    siteLabel: "carbon anion alpha to a carbonyl",
    smarts: "[C-]-[CX3](=[OX1])",
    siteAtomIndexInMatch: 0,
    pkaCenter: 20,
    pkaRange: [16, 25],
    confidence: "Low",
    atom: "The basic site is a negatively charged carbon beside a carbonyl.",
    resonance: "The charge can delocalize onto the carbonyl oxygen.",
    induction: "The carbonyl withdraws electron density and stabilizes the anion.",
    orbital: "The carbanion p orbital overlaps with the carbonyl π system.",
    explanation: "Carbonyl resonance makes this carbanion less basic than a localized alkyl carbanion.",
  },
  {
    id: "nitrile-stabilized-carbanion",
    kind: "base",
    priority: 4,
    relatedGroup: "Nitrile-stabilized carbanion",
    siteLabel: "carbon anion alpha to a nitrile",
    smarts: "[C-]-[CX2]#[NX1]",
    siteAtomIndexInMatch: 0,
    pkaCenter: 25,
    pkaRange: [23, 27],
    confidence: "Medium",
    atom: "The basic site is a negatively charged carbon beside a nitrile.",
    resonance: "The charge can delocalize toward nitrile nitrogen.",
    induction: "The nitrile strongly withdraws electron density.",
    orbital: "The carbanion can align with the nitrile π system.",
    explanation: "Nitrile stabilization lowers carbanion basicity to roughly the range of an acetylide ion.",
  },
  {
    id: "acetylide-anion",
    kind: "base",
    priority: 3,
    relatedGroup: "Acetylide anion",
    siteLabel: "acetylide carbon",
    smarts: "[C-]#[C]",
    siteAtomIndexInMatch: 0,
    pkaCenter: 25,
    pkaRange: [24, 26],
    confidence: "High",
    atom: "The basic site is a negatively charged sp carbon.",
    resonance: "Simple acetylides usually lack additional resonance stabilization.",
    induction: "Electron-withdrawing substituents reduce acetylide basicity.",
    orbital: "The sp lone pair has high s-character, stabilizing charge relative to sp2 or sp3 carbanions.",
    explanation: "Acetylide ions are strong bases, but sp hybridization makes them weaker than typical alkyl carbanions.",
  },
  {
    id: "amide-conjugate-base",
    kind: "base",
    priority: 4,
    relatedGroup: "Deprotonated amide",
    siteLabel: "amide anion nitrogen",
    smarts: "[CX3](=[OX1])[N-]",
    siteAtomIndexInMatch: 2,
    pkaCenter: 16,
    pkaRange: [14, 18],
    confidence: "Medium",
    atom: "The basic site is negatively charged nitrogen adjacent to a carbonyl.",
    resonance: "The negative charge delocalizes into the carbonyl.",
    induction: "The carbonyl withdraws electron density and stabilizes the anion.",
    orbital: "Nitrogen and the carbonyl share a conjugated p-orbital system.",
    explanation: "Resonance lowers the basicity of a deprotonated amide relative to a localized nitrogen anion.",
  },
  {
    id: "alkoxide",
    kind: "base",
    priority: 5,
    relatedGroup: "Alkoxide",
    siteLabel: "alkoxide oxygen",
    smarts: "[O-]-[CX4]",
    siteAtomIndexInMatch: 0,
    pkaCenter: 16.5,
    pkaRange: [15, 19],
    confidence: "Medium",
    atom: "The basic site is negatively charged oxygen.",
    resonance: "Simple alkoxides lack major resonance stabilization.",
    induction: "Electron-withdrawing substituents reduce alkoxide basicity.",
    orbital: "The localized oxygen lone pair readily forms an O–H bond.",
    explanation: "Alkoxides are strong bases because their conjugate acids are weakly acidic alcohols.",
  },
  {
    id: "hydroxide",
    kind: "base",
    priority: 6,
    relatedGroup: "Hydroxide",
    siteLabel: "hydroxide oxygen",
    smarts: "[OH-]",
    siteAtomIndexInMatch: 0,
    pkaCenter: 15.7,
    pkaRange: [15.5, 16],
    confidence: "High",
    atom: "The basic site is negatively charged oxygen.",
    resonance: "Hydroxide has no resonance stabilization.",
    induction: "No carbon substituents alter the charge.",
    orbital: "A localized oxygen lone pair accepts a proton to form water.",
    explanation: "Hydroxide is a strong base in water because its conjugate acid is water.",
  },
  {
    id: "guanidine",
    kind: "base",
    priority: 7,
    relatedGroup: "Guanidine",
    siteLabel: "guanidine imine nitrogen",
    smarts: "[NX3][CX3](=[NX2])[NX3]",
    siteAtomIndexInMatch: 2,
    pkaCenter: 13.6,
    pkaRange: [12.5, 14.5],
    confidence: "Medium",
    atom: "The imine-like nitrogen accepts the proton.",
    resonance: "The guanidinium conjugate acid delocalizes positive charge over three nitrogens.",
    induction: "Nitrogen substituents can tune the electron density of the central system.",
    orbital: "A conjugated nitrogen–carbon–nitrogen framework distributes charge efficiently.",
    explanation: "Exceptional resonance stabilization of guanidinium makes guanidines very strong neutral organic bases.",
  },
  {
    id: "amidine",
    kind: "base",
    priority: 8,
    relatedGroup: "Amidine",
    siteLabel: "amidine imine nitrogen",
    smarts: "[NX3][CX3](=[NX2])",
    siteAtomIndexInMatch: 2,
    pkaCenter: 12.5,
    pkaRange: [11, 13.5],
    confidence: "Medium",
    atom: "The imine-like nitrogen is the principal protonation site.",
    resonance: "The amidinium conjugate acid delocalizes positive charge over two nitrogens.",
    induction: "Substituents on either nitrogen can shift basicity.",
    orbital: "The conjugated N–C–N framework stabilizes the protonated form.",
    explanation: "Amidines are strong bases because their conjugate acids are resonance-stabilized.",
  },
  {
    id: "phosphine",
    kind: "base",
    priority: 9,
    relatedGroup: "Phosphine",
    siteLabel: "phosphorus lone pair",
    smarts: "[PX3;+0;!$([P](=O));!$([P](=S))]",
    siteAtomIndexInMatch: 0,
    pkaCenter: 9,
    pkaRange: [5, 11],
    confidence: "Low",
    atom: "The phosphorus lone pair accepts a proton.",
    resonance: "Resonance effects depend strongly on phosphorus substituents.",
    induction: "Alkyl groups generally increase phosphine basicity, while aryl groups often lower it.",
    orbital: "The phosphorus lone pair is diffuse and polarizable.",
    explanation: "Many phosphines are moderately strong bases, but their basicity varies widely with substitution.",
  },
  {
    id: "aliphatic-amine",
    kind: "base",
    priority: 10,
    relatedGroup: "Amine",
    siteLabel: "amine nitrogen lone pair",
    smarts: "[NX3;+0;!$([NH3]);!$([N][CX3](=O));!$([N][SX4](=O)(=O));!$([N][c]);!$(N=C);!$(N=N);!$([N][N,C]=[N])]",
    siteAtomIndexInMatch: 0,
    pkaCenter: 10.5,
    pkaRange: [9, 11.5],
    confidence: "Medium",
    atom: "The nitrogen lone pair accepts a proton.",
    resonance: "The lone pair is not substantially delocalized in a simple aliphatic amine.",
    induction: "Alkyl groups generally donate electron density, while electron-withdrawing groups reduce basicity.",
    orbital: "A localized sp3-like lone pair is readily available for protonation.",
    explanation: "Aliphatic amines are relatively strong neutral bases because their nitrogen lone pair is localized and available.",
  },
  {
    id: "phenoxide",
    kind: "base",
    priority: 11,
    relatedGroup: "Phenoxide",
    siteLabel: "phenoxide oxygen",
    smarts: "[c][O-]",
    siteAtomIndexInMatch: 1,
    pkaCenter: 10,
    pkaRange: [9, 11],
    confidence: "High",
    atom: "The basic site is negatively charged oxygen.",
    resonance: "Phenoxide delocalizes charge into the aromatic ring.",
    induction: "Electron-withdrawing ring substituents reduce basicity.",
    orbital: "The oxygen p orbital overlaps with the aromatic π system.",
    explanation: "Phenoxide is a strong base, but resonance makes it weaker than a typical alkoxide.",
  },
  {
    id: "thiolate",
    kind: "base",
    priority: 12,
    relatedGroup: "Thiolate",
    siteLabel: "thiolate sulfur",
    smarts: "[S-]",
    siteAtomIndexInMatch: 0,
    pkaCenter: 10.5,
    pkaRange: [9, 12],
    confidence: "Medium",
    atom: "The basic site is negatively charged sulfur.",
    resonance: "Simple thiolates usually lack major resonance stabilization.",
    induction: "Electron-withdrawing substituents reduce thiolate basicity.",
    orbital: "Large sulfur orbitals stabilize charge, reducing basicity relative to alkoxides.",
    explanation: "Thiolates are strong bases and nucleophiles, but sulfur's size makes them less basic than comparable alkoxides.",
  },
  {
    id: "carboxylate",
    kind: "base",
    priority: 13,
    relatedGroup: "Carboxylate",
    siteLabel: "carboxylate oxygen",
    smarts: "[CX3](=[OX1])[O-]",
    siteAtomIndexInMatch: 2,
    pkaCenter: 4.8,
    pkaRange: [3.5, 5.5],
    confidence: "High",
    atom: "The basic site is an oxygen bearing delocalized negative charge.",
    resonance: "The charge is shared between two oxygens.",
    induction: "Electron-withdrawing substituents reduce carboxylate basicity.",
    orbital: "The O–C–O unit forms a delocalized π system.",
    explanation: "Carboxylates are weaker bases than alkoxides because resonance strongly stabilizes the anion.",
  },
  {
    id: "aniline",
    kind: "base",
    priority: 14,
    relatedGroup: "Aniline",
    siteLabel: "aniline nitrogen lone pair",
    smarts: "[c]-[NX3;+0;!$([N][CX3](=O))]",
    siteAtomIndexInMatch: 1,
    pkaCenter: 4.6,
    pkaRange: [3.5, 6],
    confidence: "Medium",
    atom: "The nitrogen lone pair accepts a proton.",
    resonance: "The neutral amine lone pair is delocalized into the aromatic ring, reducing availability.",
    induction: "Ring substituents can strongly alter aniline basicity.",
    orbital: "The nitrogen lone pair occupies a p orbital conjugated with the ring.",
    explanation: "Anilines are weaker bases than aliphatic amines because the lone pair is partially delocalized into the aromatic ring.",
  },
  {
    id: "pyridine-like-n",
    kind: "base",
    priority: 15,
    relatedGroup: "Pyridine-like aromatic nitrogen",
    siteLabel: "aromatic nitrogen lone pair",
    smarts: "[nH0;+0]",
    siteAtomIndexInMatch: 0,
    pkaCenter: 5.2,
    pkaRange: [2, 7],
    confidence: "Low",
    atom: "The aromatic nitrogen has a lone pair available for protonation.",
    resonance: "The lone pair is outside the aromatic π sextet, so protonation can preserve aromaticity.",
    induction: "Ring heteroatoms and substituents can shift basicity over a broad range.",
    orbital: "The lone pair occupies an in-plane sp2 orbital rather than the aromatic p orbital.",
    explanation: "Pyridine-like nitrogens are moderately weak bases whose lone pair remains available without disrupting aromaticity.",
  },
  {
    id: "imine",
    kind: "base",
    priority: 16,
    relatedGroup: "Imine",
    siteLabel: "imine nitrogen lone pair",
    smarts: "[CX3]=[NX2;+0]",
    siteAtomIndexInMatch: 1,
    pkaCenter: 5.5,
    pkaRange: [3, 7],
    confidence: "Low",
    atom: "The imine nitrogen lone pair accepts a proton.",
    resonance: "Conjugation and substituents can stabilize either the neutral or protonated form.",
    induction: "Electron-withdrawing substituents generally reduce imine basicity.",
    orbital: "The lone pair occupies an sp2 orbital adjacent to a π bond.",
    explanation: "Imines are weaker bases than most aliphatic amines because the nitrogen is sp2-hybridized and conjugated with a C=N bond.",
  },
  {
    id: "amide-carbonyl-oxygen",
    kind: "base",
    priority: 17,
    relatedGroup: "Amide",
    siteLabel: "amide carbonyl oxygen",
    smarts: "[NX3][CX3](=[OX1])",
    siteAtomIndexInMatch: 2,
    pkaCenter: -1,
    pkaRange: [-2, 1],
    confidence: "Medium",
    atom: "Protonation occurs mainly at the carbonyl oxygen rather than nitrogen.",
    resonance: "The amide nitrogen donates electron density into the carbonyl, changing both protonation sites.",
    induction: "Electron-withdrawing substituents reduce oxygen basicity.",
    orbital: "An oxygen lone pair forms the new O–H bond while the amide π system reorganizes.",
    explanation: "Amides are weak bases overall; their carbonyl oxygen is generally more basic than the resonance-deactivated nitrogen.",
  },
  {
    id: "water-base",
    kind: "base",
    priority: 18,
    relatedGroup: "Water",
    siteLabel: "water oxygen lone pair",
    smarts: "[OH2;+0]",
    siteAtomIndexInMatch: 0,
    pkaCenter: -1.7,
    pkaRange: [-2.5, -1],
    confidence: "High",
    atom: "An oxygen lone pair accepts a proton.",
    resonance: "No resonance effect is present.",
    induction: "No carbon substituents alter the lone-pair electron density.",
    orbital: "An oxygen lone pair forms the new O–H bond in hydronium.",
    explanation: "Water is a weak base; protonation gives hydronium, a strong acid.",
  },
  {
    id: "alcohol-base",
    kind: "base",
    priority: 19,
    relatedGroup: "Alcohol",
    siteLabel: "alcohol oxygen lone pair",
    smarts: "[OX2H1;+0;!$([O][O]);!$([O][CX3](=O));!$([O][SX4](=O)(=O));!$([O][c])]",
    siteAtomIndexInMatch: 0,
    pkaCenter: -2,
    pkaRange: [-3, -1],
    confidence: "Medium",
    atom: "An oxygen lone pair accepts a proton.",
    resonance: "Simple alcohols lack major resonance effects.",
    induction: "Electron-withdrawing substituents reduce oxygen basicity.",
    orbital: "A localized oxygen lone pair forms the new O–H bond.",
    explanation: "Alcohols are weak bases because protonation produces a strongly acidic oxonium ion.",
  },
  {
    id: "aryl-ether",
    kind: "base",
    priority: 20,
    relatedGroup: "Aryl ether",
    siteLabel: "aryl ether oxygen lone pair",
    smarts: "[c]-[OX2;+0]-[#6]",
    siteAtomIndexInMatch: 1,
    pkaCenter: -3.5,
    pkaRange: [-5, -2],
    confidence: "Low",
    atom: "An oxygen lone pair accepts a proton.",
    resonance: "One lone pair is delocalized into the aromatic ring, lowering availability.",
    induction: "Ring substituents can alter oxygen basicity.",
    orbital: "The remaining lone pair can protonate, while the conjugated lone pair interacts with the ring.",
    explanation: "Aryl ethers are weak bases because aromatic conjugation reduces lone-pair availability.",
  },
  {
    id: "ether",
    kind: "base",
    priority: 21,
    relatedGroup: "Ether",
    siteLabel: "ether oxygen lone pair",
    smarts: "[#6]-[OX2;+0;!$([O][CX3](=O))]-[#6]",
    siteAtomIndexInMatch: 1,
    pkaCenter: -3,
    pkaRange: [-4, -2],
    confidence: "Medium",
    atom: "An oxygen lone pair accepts a proton.",
    resonance: "Simple ethers generally lack major resonance delocalization.",
    induction: "Electron-withdrawing substituents reduce oxygen basicity.",
    orbital: "A localized oxygen lone pair forms the new O–H bond.",
    explanation: "Ethers are weak bases but are readily protonated by strong acids.",
  },
  {
    id: "phenol-base",
    kind: "base",
    priority: 22,
    relatedGroup: "Phenol",
    siteLabel: "phenol oxygen lone pair",
    smarts: "[c]-[OX2H1;+0]",
    siteAtomIndexInMatch: 1,
    pkaCenter: -6,
    pkaRange: [-7, -4],
    confidence: "Low",
    atom: "An oxygen lone pair can accept a proton.",
    resonance: "Lone-pair delocalization into the ring reduces availability.",
    induction: "Ring substituents can alter phenol basicity.",
    orbital: "One oxygen lone pair overlaps with the aromatic π system.",
    explanation: "Phenols are weaker bases than ordinary alcohols because their oxygen lone pair is resonance-delocalized.",
  },
  {
    id: "ester-carbonyl-oxygen",
    kind: "base",
    priority: 23,
    relatedGroup: "Ester",
    siteLabel: "ester carbonyl oxygen",
    smarts: "[OX2H0;+0][CX3](=[OX1])",
    siteAtomIndexInMatch: 2,
    pkaCenter: -6,
    pkaRange: [-7, -4],
    confidence: "Low",
    atom: "The carbonyl oxygen is the principal protonation site.",
    resonance: "Alkoxy donation into the carbonyl changes oxygen electron density.",
    induction: "Electron-withdrawing substituents reduce carbonyl basicity.",
    orbital: "A carbonyl oxygen lone pair forms the new O–H bond.",
    explanation: "Esters are weak bases; protonation usually occurs at the carbonyl oxygen.",
  },
  {
    id: "carboxylic-acid-carbonyl-oxygen",
    kind: "base",
    priority: 24,
    relatedGroup: "Carboxylic acid",
    siteLabel: "carboxylic acid carbonyl oxygen",
    smarts: "[CX3](=[OX1])[OX2H1]",
    siteAtomIndexInMatch: 1,
    pkaCenter: -6,
    pkaRange: [-8, -4],
    confidence: "Low",
    atom: "The carbonyl oxygen can accept a proton under strongly acidic conditions.",
    resonance: "The two oxygens interact through the carbonyl system.",
    induction: "The hydroxyl oxygen lowers the carbonyl's basicity.",
    orbital: "A carbonyl oxygen lone pair forms the new O–H bond.",
    explanation: "Carboxylic acids are mainly acids and only very weak bases at oxygen.",
  },
  {
    id: "ketone-carbonyl-oxygen",
    kind: "base",
    priority: 25,
    relatedGroup: "Ketone or aldehyde",
    siteLabel: "carbonyl oxygen",
    smarts: "[CX3;!$([CX3]-[OX2,NX3,SX2])](=[OX1])",
    siteAtomIndexInMatch: 1,
    pkaCenter: -7,
    pkaRange: [-8, -5],
    confidence: "Low",
    atom: "The carbonyl oxygen lone pair accepts a proton.",
    resonance: "Protonation reorganizes the polarized C=O π bond.",
    induction: "Electron-withdrawing substituents reduce carbonyl oxygen basicity.",
    orbital: "An oxygen lone pair forms the new O–H bond.",
    explanation: "Aldehydes and ketones are weak bases that protonate at oxygen in strong acid.",
  },
  {
    id: "sulfide",
    kind: "base",
    priority: 26,
    relatedGroup: "Sulfide",
    siteLabel: "sulfide sulfur lone pair",
    smarts: "[#6]-[SX2;+0]-[#6]",
    siteAtomIndexInMatch: 1,
    pkaCenter: -5,
    pkaRange: [-7, -2],
    confidence: "Low",
    atom: "A sulfur lone pair accepts a proton.",
    resonance: "Resonance depends on attached substituents.",
    induction: "Electron-withdrawing groups lower sulfur basicity.",
    orbital: "Diffuse sulfur lone pairs are polarizable but often lower in proton affinity in water than amine lone pairs.",
    explanation: "Sulfides are weak Brønsted bases but can be protonated by strong acids.",
  },
  {
    id: "nitrile-nitrogen",
    kind: "base",
    priority: 27,
    relatedGroup: "Nitrile",
    siteLabel: "nitrile nitrogen lone pair",
    smarts: "[CX2]#[NX1]",
    siteAtomIndexInMatch: 1,
    pkaCenter: -10,
    pkaRange: [-12, -8],
    confidence: "Low",
    atom: "The nitrile nitrogen lone pair is the protonation site.",
    resonance: "The C≡N system strongly stabilizes the neutral nitrile.",
    induction: "The polarized triple bond holds electron density tightly.",
    orbital: "The lone pair is in an sp orbital with high s-character.",
    explanation: "Nitriles are extremely weak bases because the nitrogen lone pair is held tightly in an sp orbital.",
  },
  {
    id: "ammonia",
    kind: "base",
    priority: 28,
    relatedGroup: "Ammonia",
    siteLabel: "ammonia nitrogen lone pair",
    smarts: "[NH3;+0]",
    siteAtomIndexInMatch: 0,
    pkaCenter: 9.25,
    pkaRange: [9, 9.5],
    confidence: "High",
    atom: "The nitrogen lone pair accepts a proton.",
    resonance: "No resonance effect is present.",
    induction: "No carbon substituents alter the electron density.",
    orbital: "A localized nitrogen lone pair forms the new N–H bond.",
    explanation: "Ammonia is a moderately strong weak base; its conjugate acid is ammonium.",
  },
] satisfies readonly AcidBaseSiteRule[];