import type { ParsedMol } from "../../nomenclature/types";
import type { AcidityResult } from "../acidBase/analyzeAcidity";
import type { BasicityResult } from "../acidBase/analyzeBasicity";
import type { CarbanionStabilityResult } from "./anionStability";
import type { CarbocationStabilityResult } from "./cationStability";
import type { CarbonRadicalStabilityResult } from "./radicalStability";
import type { ComparisonMetric, ComparisonModeId } from "../comparisonTypes";
import {
  aromaticAndConjugation,
  carbonNeighborCount,
  emptyMetric,
  isPiAdjacent,
  metric,
  type DelocalizationSummary,
} from "../comparisonUtils";

function bestAlkeneMetric(graph: ParsedMol) {
  const candidates = graph.bonds.filter(
    (bond) =>
      bond.bondOrder === 2 &&
      graph.atoms[bond.atomA]?.element === "C" &&
      graph.atoms[bond.atomB]?.element === "C",
  );
  if (candidates.length === 0) return null;

  let best = { score: -Infinity, substitution: 0, conjugated: false };
  for (const bond of candidates) {
    const substitution =
      carbonNeighborCount(graph, bond.atomA, bond.atomB) +
      carbonNeighborCount(graph, bond.atomB, bond.atomA);
    const conjugated =
      isPiAdjacent(graph, bond.atomA, bond.atomB) ||
      isPiAdjacent(graph, bond.atomB, bond.atomA);
    const score = substitution * 2 + (conjugated ? 2.5 : 0);
    if (score > best.score) best = { score, substitution, conjugated };
  }
  return best;
}

export function applyStabilityMetrics(
  metrics: Record<ComparisonModeId, ComparisonMetric>,
  graph: ParsedMol,
  acidity: AcidityResult[],
  basicity: BasicityResult[],
  bestAnion: CarbanionStabilityResult | null,
  bestCation: CarbocationStabilityResult | null,
  bestRadical: CarbonRadicalStabilityResult | null,
): DelocalizationSummary {

  metrics.anionStability = bestAnion
    ? metric(
        -bestAnion.stabilityScore,
        `Atom ${bestAnion.chargedAtomIndex + 1} · ${bestAnion.nearestStabilizer ?? bestAnion.substitution}`,
        bestAnion.explanation,
      )
    : emptyMetric(
        "No carbon-anion site was generated by the current stability analyzer.",
      );
  metrics.cationStability = bestCation
    ? metric(
        -bestCation.stabilityScore,
        `Atom ${bestCation.chargedAtomIndex + 1} · ${bestCation.nearestStabilizer ?? bestCation.substitution}`,
        bestCation.explanation,
      )
    : emptyMetric(
        "No carbon-cation site was generated by the current stability analyzer.",
      );
  metrics.radicalStability = bestRadical
    ? metric(
        -bestRadical.stabilityScore,
        `Atom ${bestRadical.radicalAtomIndex + 1} · ${bestRadical.centerType}`,
        bestRadical.explanation,
      )
    : emptyMetric(
        "No carbon-radical site was generated by the current stability analyzer.",
      );

  const alkene = bestAlkeneMetric(graph);
  metrics.alkeneStability = alkene
    ? metric(
        alkene.score,
        `${alkene.substitution}-substituent C=C${alkene.conjugated ? " · conjugated" : ""}`,
        "Higher alkene substitution and conjugation increase the qualitative stability score.",
      )
    : emptyMetric("No carbon–carbon double bond detected.");

  const bestAcid = acidity[0];
  const bestBase = basicity[0];
  metrics.acidity = bestAcid
    ? metric(
        -bestAcid.estimatedPkaNumber,
        `pKa ≈ ${bestAcid.estimatedPka}`,
        bestAcid.explanation,
      )
    : emptyMetric("No supported acidic site detected.");
  metrics.conjugateBaseStability = bestAcid
    ? metric(
        -bestAcid.estimatedPkaNumber,
        `${bestAcid.acidicSite} · pKa ≈ ${bestAcid.estimatedPka}`,
        "A lower acid pKa implies a more stabilized conjugate base under the same comparison framework.",
      )
    : emptyMetric(
        "No supported acidic site detected from which to infer conjugate-base stability.",
      );
  metrics.basicity = bestBase
    ? metric(
        bestBase.conjugateAcidPkaNumber,
        `conjugate-acid pKa ≈ ${bestBase.conjugateAcidPka}`,
        bestBase.explanation,
      )
    : emptyMetric("No supported basic site detected.");

  const delocalization = aromaticAndConjugation(graph);
  const resonanceScore =
    delocalization.aromaticBonds * 0.6 +
    delocalization.piBonds * 1.2 +
    delocalization.adjacentPiConnections * 2;
  metrics.resonanceStabilization = metric(
    resonanceScore > 0 ? resonanceScore : null,
    resonanceScore > 0
      ? `delocalization score ${resonanceScore.toFixed(1)}`
      : "No extended delocalization detected",
    `Detected ${delocalization.aromaticBonds} aromatic bond(s) and ${delocalization.piBonds} explicit multiple bond(s).`,
  );
  metrics.aromaticStabilization = metric(
    delocalization.aromaticBonds > 0 ? delocalization.aromaticBonds : null,
    delocalization.aromaticBonds > 0
      ? `${delocalization.aromaticBonds} aromatic bond(s)`
      : "No aromatic bonds detected",
    "This compares extent of aromatic bonding, not aromatic stabilization energy in kcal/mol.",
  );
  const conjugationScore =
    delocalization.aromaticBonds +
    delocalization.piBonds +
    delocalization.adjacentPiConnections * 2;
  metrics.conjugation = metric(
    conjugationScore > 0 ? conjugationScore : null,
    conjugationScore > 0
      ? `conjugation score ${conjugationScore.toFixed(1)}`
      : "No conjugated pi system detected",
    "Higher score reflects more aromatic/multiple bonds and direct connections between pi-bonded centers.",
  );

  return delocalization;
}
