import type { FunctionalGroupPattern } from "../../types";

export const acidDerivativeGroups: FunctionalGroupPattern[] = [
  {
    name: "Peroxyacid",
    priority: 0.9,
    nomenclaturePriority: 0.9,
    confidence: "High",
    suffix: "-peroxoic acid",
    prefix: "peroxy",
    equivalentNames: ["peracid", "peroxycarboxylic acid"],
    smarts: "[CX3](=O)[OX2][OX2H]",
    mcatNote:
      "Peroxyacids contain a carbonyl attached to an O-OH group. They are powerful oxidizing agents commonly used for alkene epoxidation and Baeyer-Villiger oxidation.",
    displaySmarts: "[CX3](=O)[OX2][OX2H]",
    category: "functionalGroup",
    },
  {
    name: "Carboxylic acid",
    priority: 1,
    nomenclaturePriority: 1,
    confidence: "High",
    suffix: "-oic acid",
    prefix: "carboxy",
    smarts: "[CX3](=O)[OX2H1]",
    mcatNote:
      "Carboxylic acids are acidic because their conjugate base is resonance-stabilized. At physiological pH, they are often negatively charged carboxylates.",
    displaySmarts: "[CX3](=O)[OX2H1]",
    category: "functionalGroup",
  },
  {
    name: "Acid anhydride",
    priority: 3,
    nomenclaturePriority: 3,
    confidence: "High",
    suffix: "-oic anhydride",
    prefix: "(acyloxy)carbonyl",
    smarts: "[CX3](=[OX1])[OX2][CX3](=[OX1])",
    mcatNote:
      "Anhydrides are reactive carboxylic acid derivatives. They undergo nucleophilic acyl substitution to form acids, esters, or amides.",
    displaySmarts: "[CX3](=O)[OX2][CX3](=O)",
    category: "functionalGroup",
  },
  {
    name: "Ester",
    priority: 4,
    nomenclaturePriority: 4,
    confidence: "High",
    suffix: "-oate",
    prefix: "alkoxycarbonyl",
    smarts: "[CX3](=[OX1])[OX2][CX4,c]",
    mcatNote:
      "Esters are carboxylic acid derivatives. They are common in lipids and can undergo hydrolysis.",
    displaySmarts: "[CX3](=[OX1])[OX2]",
    category: "functionalGroup",
  },
  {
    name: "Acyl halide",
    priority: 5,
    nomenclaturePriority: 5,
    confidence: "High",
    suffix: "-oyl halide",
    prefix: "halocarbonyl",
    smarts: "[CX3](=O)[F,Cl,Br,I]",
    mcatNote:
      "Acyl halides are highly reactive carboxylic acid derivatives and readily undergo nucleophilic acyl substitution.",
    displaySmarts: "[CX3](=O)[F,Cl,Br,I]",
    category: "functionalGroup",
    },
  {
    name: "Amide",
    priority: 6,
    nomenclaturePriority: 6,
    confidence: "High",
    suffix: "-amide",
    prefix: "carbamoyl",
    smarts: "[CX3](=[OX1])[NX3]",
    mcatNote:
      "Amides are resonance-stabilized and less basic than amines. Peptide bonds in proteins are amide bonds.",
    displaySmarts: "[CX3](=[OX1])[NX3]", 
    category: "functionalGroup",
    },
  {
    name: "Primary amide",
    priority: 5.90,
    nomenclaturePriority: 5.90,
    confidence: "High",
    suffix: "-amide",
    prefix: "carbamoyl",
    equivalentNames: ["1° amide"],
    smarts: "[CX3](=[OX1])[NX3H2]",
    mcatNote:
      "Primary amides have a carbonyl attached to NH2. Their nitrogen lone pair is resonance-delocalized into the carbonyl, making them much less basic than amines.",
    displaySmarts: "[CX3](=O)[NX3H2]",
    category: "functionalGroup",
      },
  {
    name: "Secondary amide",
    priority: 5.91,
    nomenclaturePriority: 5.91,
    confidence: "High",
    suffix: "-amide",
    prefix: "carbamoyl",
    equivalentNames: ["2° amide"],
    smarts: "[CX3](=[OX1])[NX3H1][#6]",
    mcatNote:
      "Secondary amides have a carbonyl attached to NHR. Peptide bonds are usually secondary amides.",
    displaySmarts: "[CX3](=O)[NX3H1]",
    category: "functionalGroup",
    },
  {
    name: "Tertiary amide",
    priority: 5.92,
    nomenclaturePriority: 5.92,
    confidence: "High",
    suffix: "-amide",
    prefix: "carbamoyl",
    equivalentNames: ["3° amide"],
    smarts: "[CX3](=[OX1])[NX3H0]([#6])[#6]",
    mcatNote:
      "Tertiary amides have a carbonyl attached to NR2. They are resonance-stabilized and cannot donate N-H hydrogen bonds.",
    displaySmarts: "[CX3](=O)[NX3H0]",
    category: "functionalGroup",
    },
    {
  name: "Urea",
  priority: 6.15,
  nomenclaturePriority: 6.15,
  confidence: "High",
  suffix: "urea",
  prefix: "ureido",
  smarts: "[NX3][CX3](=O)[NX3]",
  displaySmarts: "[NX3][CX3](=O)[NX3]",
  mcatNote:
    "Ureas contain a carbonyl bonded to two nitrogens. They are common in biochemistry, medicinal chemistry, and protein denaturation chemistry.",
  category: "functionalGroup",
},
{
  name: "Hydroxamic acid",
  priority: 6.25,
  nomenclaturePriority: 6.25,
  confidence: "High",
  suffix: "hydroxamic acid",
  prefix: "hydroxycarbamoyl",
  smarts: "[CX3](=O)[NX3][OX2H]",
  displaySmarts: "[CX3](=O)[NX3][OX2H]",
  mcatNote:
    "Hydroxamic acids contain C(=O)-NHOH and strongly chelate metals. They appear in enzyme inhibitors.",
  category: "functionalGroup",
  },
  {
  name: "Carbamate",
  priority: 6.5,
  nomenclaturePriority: 6.5,
  confidence: "High",
  suffix: "carbamate",
  prefix: "carbamoyloxy",
  equivalentNames: ["urethane"],
  smarts: "[OX2][CX3](=O)[NX3]",
  displaySmarts: "[OX2][CX3](=O)[NX3]",
  mcatNote:
    "Carbamates (urethanes) are carbonic acid derivatives containing both an amide-like nitrogen and an ester-like oxygen attached to the same carbonyl carbon. They are common in protecting groups, pharmaceuticals, and polyurethanes.",
  category: "functionalGroup",
},
];