import type { FunctionalGroupPattern } from "../../types";

export const conjugatedCarbonyls: FunctionalGroupPattern[] = [
  {
    name: "Enal",
    priority: 8.2,
    nomenclaturePriority: 8.2,
    confidence: "High",
    suffix: "-enal",
    prefix: "formylalkenyl",
    equivalentNames: ["α,β-unsaturated aldehyde", "conjugated aldehyde"],
    smarts: "[#6]=[#6][CX3H1](=O)",
    mcatNote:
      "Enals are α,β-unsaturated aldehydes. They are conjugated electrophiles and commonly undergo Michael addition.",
  },
  {
    name: "Enone",
    priority: 8.3,
    nomenclaturePriority: 8.3,
    confidence: "High",
    suffix: "-enone",
    prefix: "oxoalkenyl",
    equivalentNames: ["α,β-unsaturated ketone", "conjugated ketone"],
    smarts: "[#6]=[#6][CX3](=O)[#6]",
    mcatNote:
      "Enones are α,β-unsaturated ketones. They can undergo both 1,2-addition and 1,4-conjugate addition.",
  },
  {
    name: "Acrolein",
    priority: 8.15,
    nomenclaturePriority: 8.15,
    confidence: "High",
    suffix: "-enal",
    prefix: "formylvinyl",
    equivalentNames: ["propenal", "acrylaldehyde"],
    smarts: "C=CC=O",
    mcatNote:
      "Acrolein is propenal, the simplest α,β-unsaturated aldehyde. It is a highly reactive Michael acceptor.",
  },
  {
    name: "Acryloyl group",
    priority: 8.5,
    nomenclaturePriority: 8.5,
    confidence: "High",
    suffix: "acryloyl derivative",
    prefix: "acryloyl",
    equivalentNames: ["α,β-unsaturated acyl group"],
    smarts: "C=CC(=O)",
    mcatNote:
      "Acryloyl groups contain a conjugated alkene-carbonyl system and are common electrophilic Michael acceptors.",
  },
  {
    name: "Acrylic acid",
    priority: 1.5,
    nomenclaturePriority: 1.5,
    confidence: "Medium",
    suffix: "acrylic acid",
    prefix: "carboxyvinyl",
    equivalentNames: ["propenoic acid"],
    smarts: "C=CC(=O)[OX2H]",
    mcatNote:
      "Acrylic acid is propenoic acid, the simplest α,β-unsaturated carboxylic acid.",
  },
  {
    name: "Enoic acid",
    priority: 1.6,
    nomenclaturePriority: 1.6,
    confidence: "Medium",
    suffix: "-enoic acid",
    prefix: "carboxyalkenyl",
    equivalentNames: ["α,β-unsaturated carboxylic acid"],
    smarts: "[#6]=[#6][CX3](=O)[OX2H]",
    mcatNote:
      "Enoic acids are α,β-unsaturated carboxylic acids. They combine carboxylic acid acidity with conjugated alkene reactivity.",
  },
  {
    name: "Crotonic acid",
    priority: 1.55,
    nomenclaturePriority: 1.55,
    confidence: "Medium",
    suffix: "crotonic acid",
    prefix: "carboxypropenyl",
    equivalentNames: ["but-2-enoic acid"],
    smarts: "CC=CC(=O)[OX2H]",
    mcatNote:
      "Crotonic acid is but-2-enoic acid, a methyl-substituted α,β-unsaturated carboxylic acid.",
  },
  {
    name: "Crotonaldehyde",
    priority: 8.16,
    nomenclaturePriority: 8.16,
    confidence: "Medium",
    suffix: "-enal",
    prefix: "formylpropenyl",
    equivalentNames: ["but-2-enal"],
    smarts: "CC=CC=O",
    mcatNote:
      "Crotonaldehyde is but-2-enal, a methyl-substituted α,β-unsaturated aldehyde.",
  },
  {
    name: "Cinnamic acid",
    priority: 1.54,
    nomenclaturePriority: 1.54,
    confidence: "Medium",
    suffix: "cinnamic acid",
    prefix: "carboxystyryl",
    equivalentNames: ["phenylpropenoic acid"],
    smarts: "c1ccccc1C=CC(=O)[OX2H]",
    mcatNote:
      "Cinnamic acid contains a phenyl-substituted α,β-unsaturated carboxylic acid system.",
  },
  {
    name: "Cinnamaldehyde",
    priority: 8.14,
    nomenclaturePriority: 8.14,
    confidence: "Medium",
    suffix: "-enal",
    prefix: "formylstyryl",
    equivalentNames: ["phenylpropenal"],
    smarts: "c1ccccc1C=CC=O",
    mcatNote:
      "Cinnamaldehyde contains a phenyl-substituted α,β-unsaturated aldehyde system and is the main flavor compound in cinnamon.",
  },
  {
    name: "Chalcone",
    priority: 8.13,
    nomenclaturePriority: 8.13,
    confidence: "Medium",
    suffix: "chalcone",
    prefix: "benzylideneacetophenone",
    equivalentNames: ["aryl enone", "1,3-diaryl-2-propen-1-one"],
    smarts: "c1ccccc1C=CC(=O)c1ccccc1",
    mcatNote:
      "Chalcones are diaryl enones. They contain an α,β-unsaturated ketone between two aromatic rings.",
  },
  {
    name: "Enamide",
    priority: 6.5,
    nomenclaturePriority: 6.5,
    confidence: "Medium",
    suffix: "-enamide",
    prefix: "enamido",
    equivalentNames: ["α,β-unsaturated amide", "alkenyl amide"],
    smarts: "[#6]=[#6][CX3](=O)[NX3]",
    mcatNote:
      "Enamides are α,β-unsaturated amides. They combine amide resonance with conjugated alkene reactivity.",
  },
  {
    name: "Enoate",
    priority: 4.5,
    nomenclaturePriority: 4.5,
    confidence: "Medium",
    suffix: "-enoate",
    prefix: "alkoxycarbonylalkenyl",
    equivalentNames: ["α,β-unsaturated ester"],
    smarts: "[#6]=[#6][CX3](=O)[OX2][#6]",
    mcatNote:
      "Enoates are α,β-unsaturated esters. They are Michael acceptors and are common in conjugate addition chemistry.",
  },
];